### ISSUE TITLE
The app won't restart automatically after being sent to the background

### ISSUE THREAD

**Issue by ziggyJ** [Microsoft/cordova-plugin-code-push#112] opened 2016-05-04 07:48 UTC
OS: iOS9.3.1
installMode: IMMEDIATE
The app is sent to background when downloading the update because it takes too long. The update can still be downloaded on the background, but the app can not automatically restart after that in the background. When I bring the app back to the foreground, the app still does not automatically restart.

What I expect is the app will still restart automatically on the background, or restart after being brought to the foreground.

**Comment by lostintangent** [comment] 2016-05-04 15:06
@ziggyJ Interesting. We haven't seen this issue before, but it definitely sounds like there is an issue with the restart logic when the app is backgrounded in the middle of the download. We'll take a look at this today and will keep you updated. Thanks!

BTW, could you confirm that the update experience works for you as long as you don't background the app?

**Comment by rub8n** [comment] 2016-05-05 17:04
Hi @ziggyJ! Where you able to verify if the update worked as expected when not putting the app on the background? I just looked into this and it was working as expected for me.

**Comment by ziggyJ** [comment] 2016-05-09 12:38
@lostintangent @rub8n Sorry for replying late. When app is running on the foreground, the update works perfectly. My update is a bit big around 9MB, and it takes a bit long on installing update step (15seconds to 1 minute, just install time not including download time). I can reproduce the issue every time when the update is big. If update is small, it usually can restart correctly.

I remember that iOS has a mechanism that when an app is downloading a file, it will still stay on running status. I guess the app is running when downloading, but during or after the install step, the system will put the app to suspended status. Maybe the plugin does not deal with the suspend and resume correctly.

**Comment by scottbommarito** [comment] 2016-05-09 17:31
Hey @ziggyJ, I just took a look at this as well. Unfortunately I'm having trouble reproducing your issue as well--even when I can get the update to take as long to install as you're describing, and when I background and foreground the app through the process, the app still restarts when the installation finishes.

However, what I'm concerned about is the install times you're reporting for your update. 9MB is actually fairly small--we've seen updates before that are 200MB--so there's no way it should be taking so long to install. In fact I just created a 1GB update to test this behavior and the install time took 15-20 seconds! I think there's an issue in the install process that makes it takes a long time on your phone and also makes it fail to restart when the install is finished.

If you could answer a couple more questions for me it would be a big help in narrowing down your issue!

1 - What iOS device are you using?

2 - When it installs and it fails to restart, does the updated version of the app load when you kill the app and restart it? What about when you background it and foreground it again after it fails to restart initially?

Thanks for your assistance!

**Comment by ziggyJ** [comment] 2016-05-17 07:37
Hi @scottbommarito, Now I can not reproduce the issue on the new build so I have no idea what happened on that build. So I close this issue, if I can reproduce it later, I will report again. 

Thanks.

**Comment by ziggyJ** [comment] 2016-05-24 07:08
I encountered same issue today. The iOS device I used is iPhone5. The update was successfully installed but app failed to restart. The syncStatus stayed as UPDATED_INSTALLED, but the app just did not restart. I added a button which called codePush.restartApplication to work around this issue. I clicked it,  the app successfully restarted and the update was successfully applied.

**Comment by geof90** [comment] 2016-05-27 01:17
@ziggyJ I could not reproduce this issue as well. I think there could be a subtle bug somewhere, but in the meantime, short of a reliable repro, you could add a listener for everytime the app resumes that checks if there is a pending package, and restarts the app immediately. That way it can be fully automated and you don't need a button. Something like

```javascript
document.addEventListener("resume", function () {
    codePush.getPendingPackage(function(update){
        if (update) {
            codePush.restartApplication();
        }
    });
});
```

**Comment by lostintangent** [comment] 2016-07-06 16:09
@ziggyJ We still haven't been able to repro this unfortunately, so I'm going to close it for now. Please re-open this if you continue to encounter this issue, and we'll try to investigate it. Thanks!

**Closed by lostintangent** 2016-07-06 16:09 UTC

**Comment by northkode** [comment] 2016-07-07 13:33
This happens to us as well but for the on next resume option.
After I get updated installed I put the app in the background and then resume it it does not restart.  I set minimum background duration to 0 to test as well.   

We have to force quick to get it to work.
