### ISSUE TITLE
Incompatible with cordova-plugin-wkwebview-engine

### ISSUE THREAD

**Issue by cindyliu-yb** [Microsoft/cordova-plugin-code-push#295] opened 2017-09-21 11:09 UTC
### Description

I am using cordova-plugin-code-push along with cordova-plugin-wkwebview-engine and in my app. It turned out the code-push caused the files routed to file:// urls instead of the local webserver (https://localhost:8080...) which makes it unable to retrieve many files on IOS devices.

The related issues are here:
[#125](https://github.com/ionic-team/cordova-plugin-wkwebview-engine/issues/125)
[#160](https://github.com/ionic-team/cordova-plugin-wkwebview-engine/issues/160#event-1258987107)

### Additional Information

* cordova-plugin-code-push version: newest
* List of installed plugins:
cordova-plugin-code-push
cordova-plugin-wkwebview-engine

Thanks!

**Comment by max-mironov** [comment] 2017-09-21 11:21
Hello @cindyliu-yb, thanks for reporting, that's a known issue, please take a look at the following comment regarding this: https://github.com/Microsoft/cordova-plugin-code-push/issues/292#issuecomment-331057583. Closing this as duplicate. Please let us know if any considerations.

**Closed by max-mironov** 2017-09-21 11:21 UTC

**Comment by ghaiat** [comment] 2017-09-21 11:45
Hello, so basically there are no fixes and you re not going to provide one? Ionic team is saying the fix needs to be on the code push plugin side, since you re modifying the method of the wkwebview
All instances of the  issue have been closed but the issue is still there...

**Comment by max-mironov** [comment] 2017-09-21 11:55
@ghaiat additional modifications are needed in order to support wkwebview because this plugin is modifying paths to files whereas code-push  relies on local file paths when looking for the updated files.  Unfortunately this work is not in the top list of MS priorities at that moment. The original issue and resolution is posted here: https://github.com/Microsoft/cordova-plugin-code-push/issues/188#issuecomment-330625235
