### ISSUE TITLE
CodePush undefine

### ISSUE THREAD

**Issue by cslmark** [Microsoft/cordova-plugin-code-push#338] opened 2017-12-23 02:44 UTC
### Description
I follew the steps with  https://www.npmjs.com/package/cordova-plugin-code-push#plugin-usage
and http://microsoft.github.io/code-push/docs/getting-started.html. And I found the cdePuh is undefine. The detail steps is show as follow.

#### First I build a cordova project
![2](https://user-images.githubusercontent.com/13198159/34316210-1b2c076a-e7cb-11e7-957b-775322f9ae82.png)
**Add Platform iOS**
![3](https://user-images.githubusercontent.com/13198159/34316256-10b29096-e7cc-11e7-8153-2ef08cd15069.png)

#### Add codePushPlugin
cordova plugin add cordova-plugin-code-push@latest
![5](https://user-images.githubusercontent.com/13198159/34316261-34631eac-e7cc-11e7-9f07-0c1365b8f8e6.png)
>Detail pic log in text
Detail:
Installing "cordova-plugin-code-push" for ios
Installing "code-push" for ios
Installing "cordova-plugin-file" for ios
Installing "cordova-plugin-file-transfer" for ios
Failed to install 'cordova-plugin-file-transfer': CordovaError: Version of installed plugin: "cordova-plugin-file@6.0.0" does not satisfy dependency plugin requirement "cordova-plugin-file@^5.0.0". Try --force to use installed plugin as dependency.
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:557:37
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Failed to install 'cordova-plugin-code-push': CordovaError: Version of installed plugin: "cordova-plugin-file@6.0.0" does not satisfy dependency plugin requirement "cordova-plugin-file@^5.0.0". Try --force to use installed plugin as dependency.
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:557:37
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
at process._tickCallback (internal/process/next_tick.js:104:9)

**So My Solution: rm cordova-plugin-file and add add cordova-plugin-file-transfer **
![6](https://user-images.githubusercontent.com/13198159/34316268-782f0d8a-e7cc-11e7-9bdc-15fc22a0f8b7.png)

#### Add your deployment keys to the config.xml file, making sure to include the right key for each Cordova platform
**I follow the link**
http://microsoft.github.io/code-push/docs/cordova.html#link-2
code-push app add sldemo ios cordova
![8](https://user-images.githubusercontent.com/13198159/34316291-ea3519b0-e7cc-11e7-95ac-7288369a2f22.png)

**I choose Staging Deployment key, and I also add access label as picture show**
![9](https://user-images.githubusercontent.com/13198159/34316305-33d18dc4-e7cd-11e7-8432-8f412a8b57c4.png)

#### add meta label in my index.html
![10](https://user-images.githubusercontent.com/13198159/34316316-5ac20d64-e7cd-11e7-8ee0-997106a14ed4.png)

#### Plugin Usage
![10](https://user-images.githubusercontent.com/13198159/34316335-c5f2bb88-e7cd-11e7-9dcf-f7bcec1b8b9c.png)

**I begin Debug with iphone with safari I found codePush is undefine, window.codePush also**
![12](https://user-images.githubusercontent.com/13198159/34316340-fd235342-e7cd-11e7-957e-e2d2751dcd3c.png)
![13](https://user-images.githubusercontent.com/13198159/34316341-fe978de2-e7cd-11e7-9282-34936e027d11.png)

### Reproduction
You can simple follow the step above, I do not what I did wrong. I just fellow the steps as documents.

### Additional Information
cordova -version   8.0.0
code-push 2.0.4 "CodePushAcquisition"
cordova-plugin-code-push 1.10.1 "CodePush"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-whitelist 1.3.3 "Whitelist"
![1](https://user-images.githubusercontent.com/13198159/34316179-901e6a28-e7ca-11e7-8ff5-b57fdb74376e.png)
reproduce on a simulator and physical device
I only Test on debug mode

(The more info the faster we will be able to address it!)

**Comment by annakocheshkova** [comment] 2017-12-23 06:16
@cslmark I think you had encountered the same issue as in [#336](https://github.com/Microsoft/cordova-plugin-code-push/issues/336). This is a known issue and we have a fix for it. Please try to intall our plugin as described in answer and see if it works. You should try this solution with a new project,  instead of `cordova plugin add cordova-plugin-code-push@latest` use `cordova plugin add https://github.com/annakocheshkova/cordova-plugin-code-push#56377533a758a0d7790c58bff00fe298deef3837 `. All the other steps you did seem right. We will wait for your feedback.

**Comment by ruslan-bikkinin** [comment] 2017-12-26 07:21
@cslmark the first part of your issue was the same as #336. We was fixed it in [v1.11.0](https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.11.0), so please upgrade your cordova-plugin-code-push to this version.
As for second part of you issue, `codepush` is undefined because you are using it in `app.initialize` method. Just place it to `app.onDeviceReady` method and it will be working like a charm.

Please let us know if it helps or any updates.

**Comment by cslmark** [comment] 2017-12-27 06:38
@ruslan-bikkinin @annakocheshkova Thank you for your help. I found that #336 method works for me to deal with codePush undefine the CLI is as follows. But I a new problem comes as the pic show. It is a good news to hear V1.11.0 fixed this problem, I will try it tomorrow. It would be great if it can solve the pic's problem also!
>cordova plugin add https://github.com/annakocheshkova/cordova-plugin-code-push.git#56377533a758a0d7790c58bff00fe298deef3837 
<img width="1110" alt="wx20171227-143350 2x" src="https://user-images.githubusercontent.com/13198159/34372931-11ad5770-eb13-11e7-9c1a-44cbbc82c5eb.png">

**Comment by ruslan-bikkinin** [comment] 2017-12-27 07:11
@cslmark seems to be that this problem is the same as https://github.com/Microsoft/cordova-plugin-code-push/issues/328. Could you please check that device or simulator where you are running your app has access to internet and hasn't any connection problems?

**Comment by ruslan-bikkinin** [comment] 2017-12-27 09:07
@cslmark Also please take a look at this https://github.com/Microsoft/cordova-plugin-code-push/issues/328#issuecomment-354080245.

**Comment by ruslan-bikkinin** [comment] 2017-12-29 12:03
@cslmark could you please tell us did you have a chance to look at this?

**Comment by cslmark** [comment] 2018-01-02 03:52
Hi @ruslan-bikkinin So sorry to reply you so late! I just had spent New Year's Day holiday last week! Today I updated my codePush plugin to V1.11.0, also had read #328. 
 You fixed the "cordova-plugin-file-transfer" and "cordova-plugin-file" no match issue, and it works well.
#328 six step didn't match my step, I didn't *Disable internet for device or simulator where you are going to deploy and run app.* anytime. And I also have the "An error occurred during sync. 0:" problem. I have never release any version to codePush platform use CLI. Does it matters?

**Comment by ruslan-bikkinin** [comment] 2018-01-05 11:59
@cslmark I tried to reproduce it but my demo app works perfectly. What I did:
1. Prepared demo app https://github.com/ruslan-bikkinin/cor338
2. Created new codepush app (`code-push app add cor338 ios cordova`) and made no releases.
3. Ran it and made sure it was working without errors:

```
2018-01-05 14:28:35.255086+0300 HelloCordova[1608:30786] Received Event: deviceready
2018-01-05 14:28:35.375768+0300 HelloCordova[1608:30786] [CodePush] Checking for update.
2018-01-05 14:28:37.074644+0300 HelloCordova[1608:30786] [CodePush] Reported status: {"status":0,"appVersion":"1.0.0","deploymentKey":"OGW4-Cw0QocqCLpIOxcP37XiF7Wsa4c23a71-4e6c-4f9b-8f95-4fb15b6dd8b5","previousLabelOrAppVersion":null,"previousDeploymentKey":null}
2018-01-05 14:28:38.179862+0300 HelloCordova[1608:30786] [CodePush] App is up to date.
```

Could you please take a look at my demo app and let me know did I miss something comparing with your case?

**Comment by sergey-akhalkov** [comment] 2018-01-08 11:28
Hi @cslmark, just a friendly ping.

**Comment by ruslan-bikkinin** [comment] 2018-01-15 08:01
I am closing this for now, please re-open if needed.

**Closed by ruslan-bikkinin** 2018-01-15 08:01 UTC
Labels: waiting-for-clarification

**Comment by cslmark** [comment] 2018-01-23 07:49
Thank you very much! And So sorry to reply late, I had solved all my problem, with latest hotCode.
