### ISSUE TITLE
ios build fails when code-push is included

### ISSUE THREAD

**Issue by thimmaiah** [Microsoft/cordova-plugin-code-push#268] opened 2017-07-18 04:58 UTC
### Description
The code for android runs well, however the ios version does not even compile if the cordova-plugin-code-push is installed.

### Reproduction
My code is at https://github.com/thimmaiah/UberNurseUI
If I try and compile it on a Mac without the cordova-plugin-code-push installed, then it compiles and runs with the following msg 

```
2017-07-18 10:13:18.328 Care Connuct[15965:2472459] WARN: Native: tried calling CodePush.sync, but the CodePush plugin is not installed.
2017-07-18 10:13:18.329 Care Connuct[15965:2472459] WARN: Install the CodePush plugin: 'ionic cordova plugin add cordova-plugin-code-push' 

```
However when I install the cordova-plugin-code-push (Ive tried it with 1.95, 1.94 & 1.93 Beta) - the compilation itself fails

### Additional Information

* cordova-plugin-code-push version:  1.9.5-beta

* List of installed plugins:
code-push 2.0.1-beta "CodePushAcquisition"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-code-push 1.9.5-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-deploy 0.6.7 "IonicDeploy"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.0.0-rc5 "PushPlugin"

* Cordova version: 7.0.1

* iOS/Android/Windows version: ios

* Does this reproduce on a debug build or release build? debug

* Does this reproduce on a simulator, or only on a physical device? its when I compile on the mac. Even before I deploy it to a sim or device. Compilation fails

> cordova build ios --device
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova build ios --device (exit code 1):
        
        (truncated) ... t-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/ArchiveIntermediates/Care\
        Connuct/BuildProductsPath/Debug-iphoneos/GoogleToolboxForMac
        -L/Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/ArchiveIntermediates/Care\
        Connuct/BuildProductsPath/Debug-iphoneos/Protobuf
        -L/Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/ArchiveIntermediates/Care\
        Connuct/BuildProductsPath/Debug-iphoneos/nanopb -F/Users/NehaiMac/work/UberNurseUI/platforms/ios/build/device
        -F/Users/NehaiMac/work/UberNurseUI/platforms/ios/Pods/FirebaseAnalytics/Frameworks
        -F/Users/NehaiMac/work/UberNurseUI/platforms/ios/Pods/FirebaseCore/Frameworks
        -F/Users/NehaiMac/work/UberNurseUI/platforms/ios/Pods/FirebaseInstanceID/Frameworks
        -F/Users/NehaiMac/work/UberNurseUI/platforms/ios/Pods/FirebaseMessaging/Frameworks -filelist
        /Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/ArchiveIntermediates/Care\
        Connuct/IntermediateBuildFilesPath/Care\ Connuct.build/Debug-iphoneos/Care\
        Connuct.build/Objects-normal/arm64/Care\ Connuct.LinkFileList -Xlinker -rpath -Xlinker
        @executable_path/Frameworks -miphoneos-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker
        /Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/ArchiveIntermediates/Care\
        Connuct/IntermediateBuildFilesPath/Care\ Connuct.build/Debug-iphoneos/Care\
        Connuct.build/Objects-normal/arm64/Care\ Connuct_lto.o -Xlinker -no_deduplicate -Xlinker -final_output -Xlinker
        /Applications/Care\ Connuct.app/Care\ Connuct -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lGoogleToolboxForMac
        -lProtobuf -lc++ -lnanopb -lsqlite3 -lz -framework AddressBook -framework FirebaseAnalytics -framework
        FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseMessaging
        -framework FirebaseNanoPB -framework StoreKit -framework SystemConfiguration -ObjC -lGoogleToolboxForMac
        -lProtobuf -lc++ -lnanopb -lsqlite3 -lz -framework AddressBook -framework FirebaseAnalytics -framework
        FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseMessaging
        -framework FirebaseNanoPB -framework StoreKit -framework SystemConfiguration
        /Users/NehaiMac/work/UberNurseUI/platforms/ios/build/device/libCordova.a -weak_framework ImageIO -framework
        CoreLocation -framework AVFoundation -lz -lPods-Care\ Connuct -lz -weak_framework AudioToolbox -Xlinker
        -dependency_info -Xlinker
        /Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/ArchiveIntermediates/Care\
        Connuct/IntermediateBuildFilesPath/Care\ Connuct.build/Debug-iphoneos/Care\
        Connuct.build/Objects-normal/arm64/Care\ Connuct_dependency_info.dat -o
        /Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/ArchiveIntermediates/Care\
        Connuct/IntermediateBuildFilesPath/Care\ Connuct.build/Debug-iphoneos/Care\
        Connuct.build/Objects-normal/arm64/Care\ Connuct
        ld: warning: directory not found for option
        '-L/Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/ArchiveIntermediates/Care
        Connuct/BuildProductsPath/Debug-iphoneos/GoogleToolboxForMac'
        ld: warning: directory not found for option
        '-L/Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/ArchiveIntermediates/Care
        Connuct/BuildProductsPath/Debug-iphoneos/Protobuf'
        ld: warning: directory not found for option
        '-L/Users/NehaiMac/Library/Developer/Xcode/DerivedData/Care_Connuct-bawquinvyquwfeaheewwcdadrhzs/Build/Intermediates/ArchiveIntermediates/Care
        Connuct/BuildProductsPath/Debug-iphoneos/nanopb'
        Undefined symbols for architecture arm64:
        "_OBJC_CLASS_$_SSZipArchive", referenced from:
        objc-class-ref in IonicDeploy.o
        objc-class-ref in ZipPlugin.o
        ld: symbol(s) not found for architecture arm64
        clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by thimmaiah** [comment] 2017-07-18 08:35
This is identical to https://github.com/Microsoft/cordova-plugin-code-push/issues/186 , but the soln described there does not work for me.

**Comment by max-mironov** [comment] 2017-07-18 08:49
Hi @thimmaiah, thanks for reporting the issue. 

So the problem is that `cordova-plugin-code-push` is not compatible with `ionic-plugin-deploy`. The former [is dependent](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/plugin.xml#L12) on `cordova-plugin-zip` and it leads to the mess that is breaking the build for ios (e.g. [this](https://github.com/MobileChromeApps/cordova-plugin-zip/blob/master/plugin.xml#L55) LOC is conflicting with [this one](https://github.com/ionic-team/ionic-plugin-deploy/blob/master/plugin.xml#L54) etc). 

You can try to do the following to verify it:
1) `cordova plugin rm  ionic-plugin-deploy --save`
2) `cordova platform rm ios`
3) `cordova platform add ios`
4) `cordova plugin add  cordova-plugin-code-push --save`
5) `cordova build ios`

After that you should be able to build without any errors.

**Comment by max-mironov** [comment] 2017-07-18 09:43
@thimmaiah I believe we could go ahead and close the issue so far. Please let us know if any concerns.

**Closed by max-mironov** 2017-07-18 09:43 UTC

**Comment by thimmaiah** [comment] 2017-07-18 11:39
Thanks @max-mironov .Problem solved. Appreciate the quick response.
