### ISSUE TITLE
Error Status 503, Service unavailable on checking for update started again.

### ISSUE THREAD

**Issue by Wallethub** [Microsoft/cordova-plugin-code-push#281] opened 2017-08-17 12:24 UTC
Hi @sergey-akhalkov,

This issue  #272 has started coming up again. Same scenario and has started since 4:45:55 AM EDT.

**Comment by max-mironov** [comment] 2017-08-18 07:09
Hello @Wallethub, thanks for sharing this. Indeed there were some problems with this and service was not fully available for short period of time but things should be settled at that moment, sorry for inconvenience. 

On our side we'll continue to monitor this closely and please let us know if the issue is fixed on your side or you still experience same problems with this.

**Comment by Wallethub** [comment] 2017-08-18 13:35
It has also stopped on our side.

**Comment by max-mironov** [comment] 2017-08-18 14:05
I'm glad to hear that things are running smooth on your side at that moment. Close this for now, will reopen if needed.

**Closed by max-mironov** 2017-08-18 14:05 UTC
