### ISSUE TITLE
Marshmallow on-demand permissions on cordova-android@5.1.0 

### ISSUE THREAD

**Issue by zwacky** [Microsoft/cordova-plugin-code-push#57] opened 2016-01-25 16:45 UTC
As soon as I'm about to install the OTA update, I'm asked to allow file storage permissions on the device. This is rather ugly and can turn users away from updating.

Probably not entirely a code-push, but maybe others stumble upon the same issue.

Can this storage permission be omitted with Marshmallow somehow? declaring in the AndroidManifest or something?

![screenshot_20160125-173154](https://cloud.githubusercontent.com/assets/1093032/12557493/55e5a048-c38b-11e5-9a77-3c501e0611b2.png)

**Comment by lostintangent** [comment] 2016-01-25 18:53
Yeah that is obviously not a good experience. Let us take a look into this and see what we can do to mitigate it. Stay tuned!

**Comment by dlebu** [comment] 2016-01-25 19:10
Thanks for reporting this issue. One of our plugin dependencies (the file transfer plugin) does add the write external storage to the Android manifest file, which under the new permission rules, is a dangerous permission. However, to my knowledge, we never use that permission since we [download the files to the application sandbox, not the phone external storage](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/www/remotePackage.ts#L79). So in theory, we should not see that permission dialog when installing the update.

Can you give me more details about your scenario?
- What kind of build are you running? Debug or release? Do I need to sign the apk?
- Were you on a device or emulator when reproducing the issue?

I tried to reproduce it on an emulator with a debug build unsuccessfully.

One quick way to fix this issue is to change your android target version to 22 like this:
```xml
<platform name="android">
        <preference name="android-minSdkVersion" value="YOUR_MIN_SDK_VERSION" />
        <preference name="android-targetSdkVersion" value="22" />
</platform>
```
Make sure your minimum sdk version is at most 22 as well. But this is not ideal and if this is a real issue we need to look into it.

**Comment by zwacky** [comment] 2016-01-26 09:56
tested on actual device (nexus 5), debug build
- using debug build

there's currently a bug in 

reproducable:
- if you use xwalk, make sure you use 15 or less (16+ problems with emulators)
-

**Comment by zwacky** [comment] 2016-01-26 09:59
popup comes:
- tested on actual device (nexus 5), debug build

popup doesn't come:
- emulator (nexus 5), debug build

**Comment by zwacky** [comment] 2016-01-26 10:39
setting the `android-targetSdkVersion` to 22 does fix it though.

**Comment by scottbommarito** [comment] 2016-03-29 18:45
I just looked into this. The bug is caused by the Cordova file plugin, which, in its current release, always asks for the storage permission with any storage operation regardless of whether or not it actually requires it. They've fixed the issue, but it's not yet released. We could a quick modification to the plugin.xml file to resolve the problem and then revert the changes once they've made a release.

`<dependency id="cordova-plugin-file" url="https://github.com/apache/cordova-plugin-file.git" commit="1e2593f42455aa78d7fff7400a834beb37a0683c" />`
`<dependency id="cordova-plugin-file-transfer" version=">=1.3.0" />`

(it is important that file is before file-transfer in the dependencies, because otherwise file-transfer's dependencies install first and ignore what we specify here)

**Comment by dlebu** [comment] 2016-03-29 18:49
The guys that fixed the bug are Microsoft employees. We should understand what is the timeline of the release before changing the dependency, since we already have a workaround.

**Comment by dlebu** [comment] 2016-04-18 16:29
@rakatyal What is the schedule for releasing a new version of the Cordova file plugin to npm? We have this related issue in the CodePush plugin.

**Comment by rakatyal** [comment] 2016-04-18 18:00
@dlebu: We have a plugin release in process right now. It should be out soon. I will update this thread once it's done.

**Comment by dlebu** [comment] 2016-04-18 18:19
@rakatyal Thanks a lot!

**Comment by rakatyal** [comment] 2016-04-19 18:48
The release has passed and I expect the npm packages to be released today or tomorrow. You can track the progress by following [this](http://markmail.org/message/dxgdypcobiijsptx) mail thread.

**Comment by lostintangent** [comment] 2016-04-20 21:15
This issue has been resolved and will be released to NPM this afternoon.

**Closed by lostintangent** 2016-04-20 21:15 UTC
Labels: bug

**Comment by bakuryu101** [comment] 2017-02-13 20:50
asdasd
