### ISSUE TITLE
Error loading from file:// URL using wkwebview-engine

### ISSUE THREAD

**Issue by chris-vaszauskas** [Microsoft/cordova-plugin-code-push#106] opened 2016-04-25 20:59 UTC
When I try to `codePush.restartApplication()` after downloading an update, I get an error something like the following in the Safari console:

`Failed to load resource    file://var/mobile/.../codepush/deploy/versions/...`

I am never able to run from the downloaded update. When I remove the wkwebview-engine plugin, everything succeeds.

Relevant versions:

- iOS engine 4.1.1
- cordova-plugin-code-push@1.6.0-beta (I'm not able to try this on 1.7.0-beta because of #105)
- cordova-plugin-wkwebview-engine@1.0.3
- cordova-plugin-file@4.2.0

**Comment by lostintangent** [comment] 2016-04-25 21:08
@chris-vaszauskas We discovered a WKWebView regression this morning which is related to this bug and the other one you filed above CORS. Apologies about this! We're investigating it right now.

**Comment by chris-vaszauskas** [comment] 2016-04-28 17:11
Update on this: now that #105 is fixed, I am able to try this with cordova-plugin-code-push@1.7.0-beta. The behavior is slightly different. I still get the `failed to load resource` error when I try to run `codePush.restartApplication()`, but when I run from a cold boot, the app loads from the updated codebase correctly.

**Comment by lostintangent** [comment] 2016-04-28 17:21
@chris-vaszauskas OK thanks for that update. We're looking into this today.

**Comment by shishirx34** [comment] 2016-05-06 19:04
@chris-vaszauskas - We believe that this issue has been fixed in 1.7.1-beta, there were couple of other related issues that has since been fixed. I tried the above repro steps and couldn't see any issues with wkwebview-engine. It would be great if you can try the latest 1.7.1-beta and verify it works for you.

I am closing this bug since it seems to be fixed, feel free to reopen this issue if it still doesn't work for you. Thank you for your patience. Please do let us know if run into any other issues using our service.

**Closed by shishirx34** 2016-05-06 19:04 UTC
Labels: bug
