### ISSUE TITLE
Android crash on startup after code-push update

### ISSUE THREAD

**Issue by Morathil** [Microsoft/cordova-plugin-code-push#264] opened 2017-07-07 09:56 UTC
### Description

Android crash after installing first code-push update.

### Reproduction

1.) Install app
2.) Release code push version
3.) Restart app (sync in background)
4.) Javascript console output:
```
[CodePush] Could not get application build time. Error: Could not get application timestamp.
[CodePush] Install succeeded.
[CodePush] Update is installed and will be run on the next app restart.
```
5.) Close app
6.) Open app
7.) Native crash 
```
Shutting down VM
FATAL EXCEPTION: main
Process: com.test.app, PID: 2996
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.app/com.test.app.MainActivity}: java
                                                            .lang.NumberFormatException: Invalid long: "1.4994191E12"
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NumberFormatException: Invalid long: "1.4994191E12"
at java.lang.Long.invalidLong(Long.java:124)
at java.lang.Long.parse(Long.java:363)
at java.lang.Long.parseLong(Long.java:353)
at java.lang.Long.parseLong(Long.java:321)
at com.microsoft.cordova.Utilities.getApkBuildTime(Utilities.java:62)
at com.microsoft.cordova.CodePush.clearDeploymentsIfBinaryUpdated(CodePush.java:277)
at com.microsoft.cordova.CodePush.onStart(CodePush.java:473)
at org.apache.cordova.PluginManager.onStart(PluginManager.java:273)
at org.apache.cordova.CordovaWebViewImpl.handleStart(CordovaWebViewImpl.java:458)
at org.apache.cordova.CordovaActivity.onStart(CordovaActivity.java:299)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
at android.app.Activity.performStart(Activity.java:6268)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
```

### Additional Information

* cordova 6.1.1
* cordova android 4.1.1
* happens on debug and release build
* also happens on code-push version 1.9.4-beta
* code push-version 1.9.2-beta seems to work fine (not tested 1.9.3-beta)

Do you have any idea what could be the problem?

Thanks!

**Comment by sergey-akhalkov** [comment] 2017-07-10 14:24
Hi @Morathil, thank you for reaching us. I believe you are experiencing the issue due to this PR https://github.com/Microsoft/cordova-plugin-code-push/pull/216.
Currently, application build time is writing here https://github.com/Microsoft/cordova-plugin-code-push/commit/021b6723f5f57100832d57cc6d4ecc07ba9f58e8#diff-7a542dfee066efafd02ae74b867867f2R53 while building your apk file. 
So could you please try to reinstall cordova-plugin-code-push with new version1.9.5 and let me know if the issue is still reproduces?

**Comment by Morathil** [comment] 2017-07-12 09:17
Hey @sergey-akhalkov 

It still happens with version `1.9.5-beta`. :(

**Comment by sergey-akhalkov** [comment] 2017-07-12 12:31
@Morathil, could you please try to replace `Long.toString(System.currentTimeMillis())` by `System.currentTimeMillis() + ""` in [build.gradle file](https://github.com/Microsoft/cordova-plugin-code-push/commit/021b6723f5f57100832d57cc6d4ecc07ba9f58e8#diff-7a542dfee066efafd02ae74b867867f2R53) and verify if it works for you?
If not, could you please provide me with a minimal version of your app where the issue is reproduce or try to reproduce it using our [sample app](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples)?

**Comment by max-mironov** [comment] 2017-07-17 07:22
@Morathil - hi, do you have a chance to look at this?

**Comment by Morathil** [comment] 2017-07-17 08:54
@sergey-akhalkov @max-mironov 
`System.currentTimeMillis() + ""` results in the same error.
I also tried  `new Date().getTime().toString()` which also results in the same error.

I added a log to the gradle file where `CODE_PUSH_APK_BUILD_TIME` is set and it looks like the system time gets set correctly there (e.g. `"1500281214176"`).

Then I added a log to `getApkBuildTime` where `CODE_PUSH_APK_BUILD_TIME` is read. And its value there is always something like `"1.4994191E12"` which cant be parsed as long and results in the above error. I'm not sure why the string long gets converted to the power of notation ...

Currently we are too busy to provide a sample app but maybe we manage this a bit later.

**Comment by sergey-akhalkov** [comment] 2017-07-17 09:29
@Morathil, thanks, please let us know if you have any updates.

**Comment by disharmonized** [comment] 2017-07-18 08:18
@Morathil i've tried to reproduce this bug using instructions you have provided, but unfortunately with no luck. It seems to be a tricky one to do. Yeah, if you will have some time, please, prepare sample app and more detailed repro scenario. If you could do it it would be much appretiated.

**Comment by sergey-akhalkov** [comment] 2017-07-28 11:46
Hey @Morathil, I believe the issue you have is the same as here https://stackoverflow.com/questions/18322770/java-long-tostring-returns-exponential-notation-format
So could you please to replace `Long.toString(System.currentTimeMillis())` with `String.format("%d", System.currentTimeMillis())` and let me know if it works?

**Comment by Morathil** [comment] 2017-08-04 11:37
Hi @sergey-akhalkov, I tried replacing `Long.toString(System.currentTimeMillis())` with `String.format("%d", System.currentTimeMillis())` but it results in the same error.

But I managed to fix the errors by replacing the following code in the `getApkBuildTime` function:
```
millis = parseLong(context.getString(
    context.getResources().getIdentifier("CODE_PUSH_APK_BUILD_TIME", "string", context.getPackageName())
));
```
with:
```
Double millisDouble = Double.parseDouble(context.getString(
    context.getResources().getIdentifier("CODE_PUSH_APK_BUILD_TIME", "string", context.getPackageName())
));
millis = millisDouble.longValue();
```

Actually i'm not fixing the fact that the string gets converted to a exponential notation format which can't be parsed to `Long`. I just parsed it in another way which allows the exponential notation format. (https://stackoverflow.com/questions/13563747/converting-exponential-value-in-java-to-a-number-format) Though i'm not sure if it behaves the exact same way as the old code. What do you think about it?

**Comment by ruslan-bikkinin** [comment] 2017-08-04 14:54
@Morathil, I found that there is a [bug](https://issuetracker.google.com/issues/37009529) in android SDK/Gradle and good guy named @jamesward created [repo](https://github.com/jamesward/AndroidStringBug) with repro of this bug and workaround for it. So, please, try to change these lines in `src/android/build-extras.gradle`

```
Long.toString(System.currentTimeMillis())
```

with

```
String.format("\"%d\"", System.currentTimeMillis())
```
and these lines in `src/android/Utilities.java`
```java
millis = parseLong(context.getString(
             context.getResources().getIdentifier("CODE_PUSH_APK_BUILD_TIME", "string", context.getPackageName())
);
```
with
```
millis = parseLong(context.getString(
             context.getResources().getIdentifier("CODE_PUSH_APK_BUILD_TIME", "string", context.getPackageName().replaceAll("\"",""))
```

Please, let us know, if this trick will work for you.

**Comment by Morathil** [comment] 2017-08-04 15:27
@ruslan-bikkinin, yes this trick also works for me, thanks!

**Comment by sergey-akhalkov** [comment] 2017-08-04 15:31
Hi @Morathil, thanks for the update!
@ruslan-bikkinin, nice catch, please feel free to create PR and fix the issue.

**Comment by ruslan-bikkinin** [comment] 2017-08-07 10:44
@Morathil, I am closing this issue because fix #276 has submitted.

**Closed by ruslan-bikkinin** 2017-08-07 10:44 UTC
Labels: android sdk, bug, fix-in-master

**Comment by heart-bool** [comment] 2017-10-13 11:24
@ruslan-bikkinin 

 1. react-native version    0.49.3
 2. react-native-code-push ^5.1.3-beta
I encountered another problem, the application started, code push suggest code update, this time in the place you modified before the reported such a mistake
     `java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                 at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                 at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                 at java.lang.Thread.run(Thread.java:761)
                                                              Caused by: com.microsoft.codepush.react.CodePushUnknownException: Error in getting binary resources modified time
                                                                 at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:160)
                                                                 at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:209)
                                                                 at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:204)
                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                 at java.lang.Thread.run(Thread.java:761) 
                                                              Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                                 at android.content.res.Resources.getText(Resources.java:335)
                                                                 at android.content.res.Resources.getString(Resources.java:381)
                                                                 at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:156)
                                                                 at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:209) 
                                                                 at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:204) 
                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                 at java.lang.Thread.run(Thread.java:761) `
Can you solve it?

**Comment by ruslan-bikkinin** [comment] 2017-10-13 11:40
@heart-bool thanks for your question. Please submit new issue in `react-native-code-push repo`, we will continue talking there as more relevent place than cordova-plugin-code-push.

**Comment by SwatiSoni-snapmint** [comment] 2020-07-15 16:27
I'm using the latest versions of ionic-cli and code Push.
Ionic-CLI 6.10.1
code-push 3.0.1 "CodePushAcquisition"
cordova-plugin-code-push 1.12.5 "CodePush"

Anyone can help what's going wrong?
