### ISSUE TITLE
isMandatory always comes true

### ISSUE THREAD

**Issue by sud80** [Microsoft/cordova-plugin-code-push#48] opened 2015-12-24 12:42 UTC
I did a hot code push without mandatory flag. When I run,
code-push deployment ls <app-name>

It shows Mandatory: No

But the updateCheck api always returns "isMandatory": true

Can you check on this.

**Comment by lostintangent** [comment] 2015-12-24 17:06
Hey @sud, we recently made a change that would "convert" a non-mandatory update into mandatory of there was a mandatory update released that the end-user never got. 

For example, imagine you released v1 as non-mandatory, v2 as mandatory and then v2 as non-mandatory. If a user is running v1, then the update check will return v3, but it will mark it as mandatory since the user never got v2. However, if the user is running v2, then the update check will not v3 convert to mandatory since they already received the mandatory update.

We made this change yesterday after lots of feedback. Could you verify that this is the behavior you are seeing? It would be a bug if you're always seeing the mandatory flag get set no matter what you do.

**Comment by dlebu** [comment] 2016-01-04 17:07
@sud80 I verified the behavior and it is as expected. The service behaves as @lostintangent described it in the previous reply. Closing this issue as this is by design.

**Closed by dlebu** 2016-01-04 17:07 UTC

**Comment by jasonhutchens** [comment] 2016-12-30 09:04
I'm seeing something like this (running `1.8.2-beta`) on iOS and Android:

- I confirm that the app has updated itself to the most recent version (I see it in the install metrics when running `code-push deployment history`, and we show the label in-app to confirm)
- Also confirm that running `codePush.sync` returns `SyncStatus.UP_TO_DATE`
- I then push a non-mandatory update, and `codePush.checkForUpdate`
- The `remotePackage.isMandatory` returns `true`
- However, when running `codePush.sync`, the dialog indicates that the update is not mandatory (i.e. there is an "ignore" button)
- Running `code-push deployment history` confirms the update is non-mandatory
- There _are_ mandatory updates in the history for the same binary version (which is `0.21.x`); some of these would have been skipped I presume because there were several mandatory updates in a row, and I guess the app would have updated to the most recent one
