### ISSUE TITLE
CodePush does not work with cordova-labs-local-webserver

### ISSUE THREAD

**Issue by clauderic** [Microsoft/cordova-plugin-code-push#188] opened 2016-11-21 16:37 UTC
Opening a new issue for this as suggested in #134.

It was suggested in #134 that using https://github.com/Telerik-Verified-Plugins/WKWebView was a suitable workaround. While this is true, it comes at a cost, as Telerik's WKWebView plugin does *not* support Cordova-iOS-4.

Are there any plans to solve this in the near future / what would be the next steps to help move this forward?

**Comment by silhouettes** [comment] 2016-11-21 22:20
Hi @clauderic, thanks for filing this. My apologies - as we are a little under-resourced, especially as the holiday season is coming up, it may be a few months before we are able to address this. If there is anybody from the community who has input or would like to submit PR's, we will gladly accept them!

**Comment by MatthieuHahn** [comment] 2017-01-27 16:05
Hi, I have the same issue.
Everything works fine until I try to install the update in the app.
The installation fails because it can't find the start page.
Have you got any idea when you will be able to fix this issue ? Or has it been fixed in the meanwhile ?

**Comment by max-mironov** [comment] 2017-02-23 13:30
Hi @MatthieuHahn, sorry for slow response. Do you still have the issue you posted?
If yes - can you be more specific about the symptoms? List of used plugins/platforms, is it reproduced with base sample or not etc could also help us.

**Comment by kairun** [comment] 2017-03-01 00:06
Hi, I guess I am having the same issue, as @clauderic and @MatthieuHahn.

Below are the plugins I have on my project
cordova-labs-local-webserver 2.4.0 "CordovaLocalWebServer"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crosswalk-webview 2.2.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.2-dev "File"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.1 "Cordova WKWebView Engine"
cordova-sqlite-storage 1.4.9 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

"cordova-labs-local-webserver" and "cordova-plugin-wkwebview-engine" pair is used to take advantage of wkwebview on the new iOS devices (the project don't support < iOS 9).

as soon as I add cordova-plugin-code-push@latest to the project, the iOS app breaks and never starts.




below is the error I've got from xcode when running the app

2017-03-01 11:04:09.841565 {{ myAppName }}[2117:323073] Apache Cordova native platform version 4.3.1 is starting.
2017-03-01 11:04:09.843553 {{ myAppName }}[2117:323073] Multi-tasking -> Device: YES, App: YES
2017-03-01 11:04:10.134395 {{ myAppName }}[2117:323073] CDVWKWebViewEngine will reload WKWebView if required on resume
2017-03-01 11:04:10.134569 {{ myAppName }}[2117:323073] Using WKWebView
2017-03-01 11:04:10.136883 {{ myAppName }}[2117:323073] [CDVTimer][handleopenurl] 0.405967ms
2017-03-01 11:04:10.147554 {{ myAppName }}[2117:323073] [CDVTimer][intentandnavigationfilter] 10.388017ms
2017-03-01 11:04:10.148074 {{ myAppName }}[2117:323073] [CDVTimer][gesturehandler] 0.285029ms
2017-03-01 11:04:10.196132 {{ myAppName }}[2117:323073] [CDVTimer][statusbar] 47.846019ms
2017-03-01 11:04:10.239530 {{ myAppName }}[2117:323073] [CDVTimer][file] 43.133020ms
2017-03-01 11:04:10.249673 {{ myAppName }}[2117:323073] [CDVTimer][cordovalocalwebserver] 9.878993ms
2017-03-01 11:04:10.270291 {{ myAppName }}[2117:323073] [CDVTimer][splashscreen] 20.402968ms
2017-03-01 11:04:10.276653 {{ myAppName }}[2117:323073] [CDVTimer][keyboard] 6.009996ms
2017-03-01 11:04:10.279224 {{ myAppName }}[2117:323073] [CDVTimer][codepush] 2.300024ms
2017-03-01 11:04:10.279427 {{ myAppName }}[2117:323073] [CDVTimer][TotalPluginStartup] 143.061042ms
2017-03-01 11:04:10.281036 {{ myAppName }}[2117:323073] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'http://localhost:5984/www/index.html?cdvToken=A8DF6CA5-E8AF-4BCD-A51F-682160F8D4AD-2117-0000010EA4197ED3 is not a file URL'
*** First throw call stack:
(0x1ce58df7 0x1c0bb077 0x1ce58d3d 0x251cbd2d 0x1ecf19 0x1f819d 0x202c07 0x1f8019 0xf7be3 0x21f048db 0x21f044c7 0x21f0abb3 0x21f080b5 0x21f7a439 0x1fba91 0xf79b9 0x21f76733 0x22182e29 0x22188447 0x2219b131 0x2218582d 0x1e74e9b3 0x1e74e86d 0x1e74eb57 0x1ce1471b 0x1ce14225 0x1ce124fb 0x1cd61533 0x1cd61341 0x21f6fec1 0x21f6a551 0xf78b3 0x1c52b50b)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by kairun** [comment] 2017-03-01 00:40
Hi, update on the issue that I am experiencing,

I assume that the installing with the '@latest' flag should work as v1.5.1-beta+ is required, as specified on the readme, and '@latest' installs 1.9.3-beta,

Just for a trial I added 'v.1.5.1-beta', and everything works fine (NSInvalidArgumentException is not emitted anymore with v1.5.1.-beta) until update is done, as the plugin could not find the starting page which was served through local web server.

**Comment by max-mironov** [comment] 2017-03-01 12:19
Hello @kairun, thank you so much for your investigation. Today I've tried to repro this issue. I've done the following:
1) Used our [sample](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic) app as a project
2) Added cordova-plugin-wkwebview-engine 1.1.1 "Cordova WKWebView Engine" and cocoon-cordova-labs-local-webserver 2.4.1 "CordovaLocalWebServer (Cocoon Mod)" plugins
3) Added latest code-push plugin 
4) Added ios platform
5) Build and run the app

So after all these steps I was able to build and run the app without errors.

Here is my list of installed plugins:

> cocoon-cordova-labs-local-webserver 2.4.1 "CordovaLocalWebServer (Cocoon Mod)"
code-push 1.9.0-beta "CodePushAcquisition"
cordova-plugin-code-push 1.9.3-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.1 "Notification"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.1 "Cordova WKWebView Engine"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"

btw cordova-labs-local-webserver [github page ](https://github.com/apache/cordova-plugins/blob/master/local-webserver/plugin.xml)leads me to 404, so I've taken this plugin from [here](https://github.com/ludei/cordova-plugins/tree/master/local-webserver).

My output from xCode:

> 2017-03-01 15:08:54.980 CodePushBasic[8936:107558] Apache Cordova native platform version 4.2.1 is starting.
2017-03-01 15:08:54.982 CodePushBasic[8936:107558] Multi-tasking -> Device: YES, App: YES
2017-03-01 15:08:54.994 CodePushBasic[8936:107558] 
2017-03-01 15:08:55.071 CodePushBasic[8936:107558] CDVWKWebViewEngine will reload WKWebView if required on resume
2017-03-01 15:08:55.071 CodePushBasic[8936:107558] Using WKWebView
2017-03-01 15:08:55.072 CodePushBasic[8936:107558] [CDVTimer][handleopenurl] 0.117958ms
2017-03-01 15:08:55.077 CodePushBasic[8936:107558] [CDVTimer][intentandnavigationfilter] 3.466964ms
2017-03-01 15:08:55.079 CodePushBasic[8936:107558] [CDVTimer][gesturehandler] 0.169992ms
2017-03-01 15:08:55.081 CodePushBasic[8936:107558] [CDVTimer][codepush] 0.981033ms
2017-03-01 15:08:55.102 CodePushBasic[8936:107558] [CDVTimer][file] 19.735992ms
2017-03-01 15:08:55.115 CodePushBasic[8936:107558] [CDVTimer][cordovalocalwebserver] 13.279974ms
2017-03-01 15:08:55.116 CodePushBasic[8936:107558] [CDVTimer][TotalPluginStartup] 43.502986ms
2017-03-01 15:08:58.250 CodePushBasic[8936:107558] THREAD WARNING: ['Notification'] took '65.995850' ms. Plugin should use a background thread.
2017-03-01 15:09:02.208 CodePushBasic[8936:107558] THREAD WARNING: ['Notification'] took '10.002197' ms. Plugin should use a background thread.

Can you try to reproduce this on Sample App? Is it something that I've missed or any more steps are needed to repro this?

**Comment by kairun** [comment] 2017-03-02 00:22
Hi @max-mironov 

Thanks for the quick turnaround!

I've just tried with the sample app, and have the same error.

I've cloned the sample/basic app,
1. removed the cordova-plugin-code-push from config.xml
2. cordova-plugin-code-push@latest --save
3. cordova plugin add cordova-plugin-wkwebview-engine --save
4. cordova plugin add https://github.com/apache/cordova-plugins#local-webserver --save
5. cordova platform add ios
6. cordova prepare

and ran the app in xcode against my iPhone6,

I still get this error

2017-03-02 11:21:15.170434 CodePushBasic[3542:449593] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'http://localhost:55985/www/index.html?cdvToken=35948C35-A459-4989-A3EA-146A00A68B3D-3542-0000020356F682FF is not a file URL'

Thanks for looking at the issue, let me know if there's anything I can do to make the process faster

**Comment by max-mironov** [comment] 2017-03-02 12:31
Thanks @kairun, I was able to repro an issue and will try to look at this.

**Comment by thomasbaggio** [comment] 2017-03-20 15:25
@max-mironov I have the same issue, I hope you will find a solution. Thanks a lot!

**Comment by GabrielStetco** [comment] 2017-05-25 12:02
Hello,
I have the same problem. Any news when is this going to be planned?

Thank you

**Comment by max-mironov** [comment] 2017-05-26 05:49
Hello @GabrielStetco, @thomasbaggio  - we are really very sorry about the inconvenience here but currently we are hardly backlogged and working on other highly requested features, hope we'll have time in future and revisit it back soon.

**Comment by GabrielStetco** [comment] 2017-05-26 16:20
Thanks for the update Max @max-mironov.
Unfortunately, we will need to switch to a different solution if this is not solved in a reasonable time.
I really appreciate your work.

Best regards
Gabriel

**Comment by Webrusterkk** [comment] 2017-07-07 12:45
Any Update on this?

**Comment by max-mironov** [comment] 2017-07-10 06:11
Hey @Webrusterkk, unfortunately at that moment we are focused on other work items and didn't manage to start working on this. 
Also guys if anyone could help the community with PR that should implement this item - that would be very much appreciated.

**Comment by Webrusterkk** [comment] 2017-07-10 12:15
@max-mironov  definitely will help but need some guidance and what are the possible (Optimal solution) for this problem ..

**Comment by pniko** [comment] 2017-09-19 18:13
There aren't currently any plans to continue investigating this issue with 3rd party plugins due to other priorities. If someone is willing to create a PR for this we will be happy to review and merge it in. Closing this for now.

**Comment by andrewoodleyjr** [comment] 2017-11-20 08:24
+1

**Comment by jpike88** [comment] 2017-12-29 01:21
'other' priorities? This is an absolutely critical, high priority concern for any modern SPA implementation. I would suggest that this is treated a little more seriously.

**Comment by ntbnnt** [comment] 2018-01-20 05:33
Yeah, we are basically going to have to abandon code push for something else if we can't get this working with WKWebview. I hope this is reconsidered, it's been a real pain for our team.

**Comment by jpike88** [comment] 2018-01-20 06:44
@ntbnnt we've decided to ditch iOS 8 and therefore the need for the localwebserver plugin.

I wish the CodePush team had better leadership and was clear about where things were at, but I don't have time to wait for them.

**Comment by pniko** [comment] 2018-01-21 01:56
I hear the feedback - reopening this to reevaluate things. @max-mironov and @sergey-akhalkov let's discuss this next week.

**Comment by sithwarrior** [comment] 2018-01-24 12:00
Just want to add, that this is very important to us. We cant live without the performance enhancements of **WKWebView**.

Please also note that **UIWebView** has actually been  **deprecated since IOS8***, and Ionic is now using **WKWebView** as default for new apps**.

I love the stuff you are doing with code push, and the features are top notch, but this is sadly a dealbreaker.

*https://developer.apple.com/documentation/uikit/uiwebview
**https://ionicframework.com/docs/wkwebview/

**Comment by pniko** [comment] 2018-01-24 18:47
We are currently heads down on a major update to CodePush, but prioritized this right after that release. I want to make sure we can deliver better crash/rollback support to all users before moving on to this one, but we'll get to it sometime soon. It's on my radar to push through.

**Comment by iTOYS** [comment] 2018-02-01 15:08
@silhouettes @jpike88 

Hi guys!
Seems like `cordova-plugin-wkwebview-engine` works perfectly with code-push on iOS >= 9
And the only problem I see, is work with [cordova-plugins#local-webserver](https://github.com/apache/cordova-plugins#local-webserver) Which is only needed for WKWebView support on iOS 8.

So, if you don't need iOS 8 support, you don't need `local-webserver` and can use `cordova-plugin-wkwebview-engine` without any restriction, do you?

**Comment by jpike88** [comment] 2018-02-01 15:16
Yeah I've made the jump to a non-local web server iOS setup, it's ok (although I needed https://github.com/oracle/cordova-plugin-wkwebview-file-xhr to fix an issue)

**Comment by Zakeelm** [comment] 2018-02-11 04:51
Hey everyone,

I'm closing this issue. After many hard conversations, we have decided to no longer put additional resources into iOS 8 support in App Center and CodePush. Doing so will allow us to focus on giving you other features. The team has decided that our focus going forward will be completing the rewrite of our SDK's, which will ultimately allow us to give you detailed and more reliable rollbacks and JS crash information.

**Closed by Zakeelm** 2018-02-11 04:51 UTC
Labels: enhancement

**Comment by saschwarz** [comment] 2018-02-11 13:31
@Zakeelm It's *not* iOS 8! It's all the *current* Cordova and Ionic apps for *both* iOS *and* Android that you are abandoning. Cordova and Ionic apps use WkWebView for better performance over UIWebView and since they use the same JS code for both iOS and Android you are forcing devs on Cordova/Ionic to abandon AppCenter and CodePush.

**Comment by jpike88** [comment] 2018-02-11 15:18
@saschwarz not that I'm defending @Zakeelm's decision (I think for a Microsoft owned business this is definitely sub par)... but, you can use WKWebView without the need for a local web server, assuming that you don't care about iOS8. The only trick is ensuring that CORS is bypassed on WKWebView with the above plugin link I put in.

**Comment by kairun** [comment] 2018-02-12 02:45
Hmm although I think ditching iOS8 is reasonable now, but isn't question here is if iOS8 support is the **only** usecase of the cordova local webserver plugin before closing this issue (which no one  so far happened to raise in this thread)?

**Comment by jpike88** [comment] 2018-02-12 05:18
At this point, iOS8 would be the only REAL reason anyone would be stuck with using the local web server. Otherwise, you can transition back to file:// with full functionality as far as I know (make sure you install cordova-plugin-wkwebview-file-xhr).

**Comment by saschwarz** [comment] 2018-04-08 20:06
This appears to be the solution: https://github.com/Microsoft/cordova-plugin-code-push/issues/371
