### ISSUE TITLE
invalid window.location.href after codePush

### ISSUE THREAD

**Issue by haris44** [Microsoft/cordova-plugin-code-push#365] opened 2018-02-10 15:30 UTC
Hello

I've a problem when I create an update with code-push

During a basic compilation (use cordova run android), when I navigate to an another page (page2.html), window.location.href is "file:///android_asset/www/page2.html"

But after a code push deployment, window.location.href value never change (always "...index.html")

Can you help me ? 

Best regards

Alexandre BERTRAND

**Comment by alexandergoncharov** [comment] 2018-03-15 08:13
Hi @haris44 

Thanks for reporting!
I tried to reproduce your issue but attempts were unsuccessful.
I checked it if we go to link on other page and after updating app(update contain link on one more other page) and go to this link. Window.location.href is correct on all pages.

Could you please provide some part of your code which can help me to reproduce this issue or more detailed repro steps?
Also, it will be fine if you provide version of you Android and are you using emulator or real device?

Thanks!

**Comment by iTOYS** [comment] 2018-04-02 16:20
@haris44 
Just a friendly ping! 
Still reproduce?

**Comment by alexandergoncharov** [comment] 2018-04-05 15:37
Hi @haris44,

I still can't reproduce issue without some part of your code or test project and I'll close this issue, but if it is still reproduce and affect you please feel free to re-open it.

Thanks,
Alexander

**Closed** 2018-04-05 15:37 UTC
Labels: waiting-for-clarification
