### ISSUE TITLE
Error when installing plugin in project with multiple platforms

### ISSUE THREAD

**Issue by dymo** [Microsoft/cordova-plugin-code-push#258] opened 2017-06-19 05:40 UTC
### Description

Adding the plugin to a project with a single platform works, but it fails if there are multiple platforms.

It is probably related to #243, maybe plugman have a problem with the beta tag?

### Reproduction

If I create a project with one platform like this, then it works fine:

```
cordova create myapp
cd myapp
cordova platform add android
cordova plugin add cordova-plugin-code-push@latest
```

but if I replace:

```
cordova platform add android
```

with:

```
cordova platform add android ios
```

then I get this error when adding the plugin:

Failed to install 'cordova-plugin-code-push': CordovaError: Version of installed plugin: "code-push@2.0.1-beta" does not satisfy dependency plugin requirement "code-push@>=1.9.0-beta".

### Additional Information

Windows 10 Pro
node 6.11
npm 5.0.3
cordova 7.0.1

**Comment by jdgeier** [comment] 2017-06-22 14:21
I've got the same issue.

**Comment by max-mironov** [comment] 2017-07-03 13:45
Hi there @dymo and @jdgeier. Thank you so much for reaching us. 

So basically the problem is as follows:
**Cordova7** has changed logic which they have used previously to `installDependency `method.
Please compare [Cordova6.5](https://github.com/apache/cordova-lib/blob/6.5.0/cordova-lib/src/plugman/install.js#L430) vs [Cordova7](https://github.com/apache/cordova-lib/blob/1a28929564d32d8a85dca039ee8f34656c594dfd/src/plugman/install.js#L539) implementation. 
As you can see latest implementation has [additional logic](https://github.com/apache/cordova-lib/blob/1a28929564d32d8a85dca039ee8f34656c594dfd/src/plugman/install.js#L563) with `semver.satisfies` check. 
[Here ](https://github.com/npm/node-semver#prerelease-tags)it is described some special aspects on how semver deals with prerelease tags (also [see ](https://github.com/npm/node-semver/issues/130#issuecomment-120988399)this related comment about it).  So at the end we have the following result:
```
>  semver.satisfies('2.0.1-beta','>=1.9.0-beta' , true)
false
```

At that moment I believe that @jdgeier solution should work and adding `--force` could help to avoid such unpleasant results. 

I'm not sure if we could do something with this unless we get rid of prerelease tag or probably put an empty string instead of `>=1.9.0-beta` range. 
Please share your thoughts about this or if you see any other solutions/workarounds

**Comment by max-mironov** [comment] 2017-07-04 14:00
Hi guys, finally we decided for now to update dependency to match the exact version of `code-push` package. We have released new version of cordova-code-push-plugin [1.9.5-beta](https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.9.5-beta), you can update and verify.
I'm closing the issue for now, please feel free to voice your concerns if any.

**Closed by max-mironov** 2017-07-04 14:00 UTC
