### ISSUE TITLE
iOS cordova-plugin-code-push@1.7.0-beta CORS error on OPTIONS preflight request

### ISSUE THREAD

**Issue by chris-vaszauskas** [Microsoft/cordova-plugin-code-push#105] opened 2016-04-25 20:55 UTC
On iOS, when running cordova-plugin-code-push@1.7.0-beta, I receive the following error: `Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin.` This makes sense to me given the request and the response: before making the `GET /updateCheck` request, an OPTIONS preflight request is sent with a `null` Origin header (since we are coming from a file:// URL). The response doesn't contain an Access-Control-Allow-Origin header, meaning the request is denied by CORS.

When I downgrade to cordova-plugin-code-push@1.6.0, I don't get the CORS error, but I also don't see the OPTIONS preflight request in the Safari Network inspector.

**Comment by lostintangent** [comment] 2016-04-25 21:09
@chris-vaszauskas Thanks for filing this! We're investigating our WKWebView regressions right now. Stay tuned!

**Comment by lostintangent** [comment] 2016-04-25 21:46
We just realized that `v1.7.0` added a custom header to the `/updateCheck` request which is what causes the WebView to begin send the OPTIONS preflight (and why it doesn't occur when you downgrade to `v1.6.0`). On the positive side, this is purely a server bug, since we just need to add CORS preflight support, and won't require upgrading the plugin. We'll get this fix out ASAP!

**Comment by lostintangent** [comment] 2016-04-26 01:34
FYI, the fix for this is out in code review and should be deployed to the server tomorrow.

**Comment by ryuyu** [comment] 2016-04-27 00:39
We just released an update to the code-push service that should fix this issue, so i'm going to go ahead and close it for now. Please reopen and let us know if you continue to see this. Thanks!

**Closed by ryuyu** 2016-04-27 00:39 UTC
