### ISSUE TITLE
Delay while checking for update (Only on first update)

### ISSUE THREAD

**Issue by mahesth** [Microsoft/cordova-plugin-code-push#275] opened 2017-08-03 13:07 UTC
I am checking for a new update on deviceready event and facing a delay in checking & installing updates on first update. Also when first update happening, whole www content is getting downloaded instead of the delta changes.

Below is the flow i have tried.

1. Install APK on device. (Meanwhile new updates are pushed to CodePush).
2. Open the app, on deviceready event - call codePush.sync function.
3. sync function gives out sync status of "CHECKING_FOR_UPDATE"
4. After 7-9 minutes, new package is getting downloaded (Not the diff, whole www content downloaded)
5. Re-open the app.
6. No delay in the updates check.

Issue is the delay when check and installing the update for the first time. Following updates check and install is faster and as expected.
Attaching the code-push debug screenshot for reference.

![codepush_update_delay](https://user-images.githubusercontent.com/25684319/28922928-9feecb3e-7879-11e7-94e7-cb89520bea45.png)

![codepush_update_delay_chrome_inspect](https://user-images.githubusercontent.com/25684319/28923130-9312e570-787a-11e7-86f7-fd8aa5f3b132.png)

Below is the code block i am using for sync.

```
var onProgress = function (downloadProgress) {
    var downloadPercentage = ((downloadProgress.receivedBytes / downloadProgress.totalBytes) * 100);
    console.log('Download Percentage', downloadPercentage);
});
document.addEventListener('deviceready', function() {
    codePush.sync(function(status) {
        console.log(status, SyncStatus);
    }, {installMode: InstallMode.IMMEDIATE}, onProgress);
});
```
**Could not able to figure out what i was doing wrong. Please help us on fixing this issue.**

### Additional Information

* cordova-plugin-code-push version: 1.9.5-beta
* List of installed plugins:
1. code-push 2.0.1-beta "CodePushAcquisition"
2. cordova-plugin-code-push 1.9.5-beta "CodePush"
3. cordova-plugin-compat 1.1.0 "Compat"
4. cordova-plugin-console 1.0.7 "Console"
5. cordova-plugin-device 1.1.6 "Device"
6. cordova-plugin-dialogs 1.3.3 "Notification"
7. cordova-plugin-file 4.3.3 "File"
8. cordova-plugin-file-transfer 1.6.3 "File Transfer"
9. cordova-plugin-geolocation 2.4.3 "Geolocation"
10. cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
11. cordova-plugin-network-information 1.3.3 "Network Information"
12. cordova-plugin-splashscreen 3.2.2 "Splashscreen"
13. cordova-plugin-statusbar 2.1.3 "StatusBar"
14. cordova-plugin-whitelist 1.2.2 "Whitelist"
15. cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
16. ionic-plugin-keyboard 2.2.1 "Keyboard"

* Cordova version: 6.5.0
* Android version: 5
* App was tested on a real device.

**Comment by ruslan-bikkinin** [comment] 2017-08-03 14:07
Hi, @mahesth and thanks for your question. Yes, first update will always contain full app bundle, because diffing are taking place on server, not on user's device. The reason is that we cannot trust apk/ipa content and use it as starting point for diff. Plugin downloads latest version of bundle to device and use it as starting point for diff instead. In your case, application has not any updates installed on device, so server responds with latest version of bundle, which is the first one you have just released.

**Comment by mahesth** [comment] 2017-08-03 18:14
Hi @ruslan-bikkinin, thanks for your update. Downloading full bundle at the start is fine but to check and downloading the latest bundle is what taking much time. For the update to trigger it takes around 9 mins. 
Can you help me out and let me know if anything I have missed

**Comment by ruslan-bikkinin** [comment] 2017-08-04 07:53
@mahesth full bundle will be downloaded only in case when there is no other bundles been downloaded on device. If bundle has been downloaded already and stored on user's device, server will compare its version with the latest version, then perform diffing between them and respond with diff's result.

**Comment by mahesth** [comment] 2017-08-04 07:58
@ruslan-bikkinin yes. I am able to see the diffing working for further updates. But the issue is to trigger the first update, it is taking time. You can refer the update timeline in the attached code-push debug screenshot (Update on first time). It is stuck for a while after reported status as "0" and after some time it started downloading the update.

**Comment by ruslan-bikkinin** [comment] 2017-08-04 08:07
@mahesth oh, I am sorry, now i see the thing. Yes, that's strange, we will think about it and keep you posted. all right?

**Comment by mahesth** [comment] 2017-08-04 08:25
Sure. Thank you.

**Comment by ruslan-bikkinin** [comment] 2017-08-04 08:29
This issue may be related with #221, #172.

**Comment by mahesth** [comment] 2017-08-04 09:22
@ruslan-bikkinin Yes. it seems more related to #172 since the delay is happening only at the first update. 
Any other way / workaround to overcome this issue ?

**Comment by ruslan-bikkinin** [comment] 2017-08-04 10:24
@mahesth, how many files your `assets/www` contains?

**Comment by mahesth** [comment] 2017-08-04 10:57
Around 1.8k files including images and bower library files.

**Comment by ruslan-bikkinin** [comment] 2017-08-04 12:34
Well, yes, it seems to be that hashing stucks trying to process such number of files. In this case makes sense for you to use bundlers like [webpack](https://webpack.github.io/) to decrease number of files in client build.

**Comment by mahesth** [comment] 2017-08-05 07:31
Thanks @ruslan-bikkinin . So the root cause for the delay is because of the number of files in the www folder. In case of bundling the files together might help us in first run, but in case of a small change in a file will result in increase of the updates size right ? ..

**Comment by ruslan-bikkinin** [comment] 2017-08-07 06:57
> but in case of a small change in a file will result in increase of the updates size right ?
Yes, you are right.

> The majority of number of files in the app www folder is in bower libraries & HTML templates.
In that case you can bundle bower libraries and you app code separately, because bower packages are changing not so often as app.

**Comment by sergey-akhalkov** [comment] 2017-08-09 14:15
Closing this as duplicate of https://github.com/Microsoft/cordova-plugin-code-push/issues/172
@mahesth, please feel free to continue discussion in #172 and let us know if you have any questions.

**Closed by sergey-akhalkov** 2017-08-09 14:15 UTC
Labels: duplicate, question
