### ISSUE TITLE
code-push not updating on iphone deviсes

### ISSUE THREAD

**Issue by siddushar** [Microsoft/cordova-plugin-code-push#274] opened 2017-08-02 14:42 UTC
I am trying to using code push my ionic2 app. it works with android device. but when i release for ios device it will not update on mobile device. it download packages and sync also works well but changes not reflecting on ios devices.

#plugins installed
* cordova-plugin-code-push version: 1.7.1-beta
* code push version 2.0.2-beta
* Cordova version: 6.5.9
* iOS: 4.3.1
* Does this reproduce on a debug build or release build? : debug
* Does this reproduce on a simulator, or only on a physical device?: both

**Comment by max-mironov** [comment] 2017-08-03 15:13
Hi there @siddushar and thanks for reaching us. I've tried new Ionic2 app on ios and I was able successfully to apply the update. Do you have different deployment keys for ios/android? 

BTW you are using pretty outdated plugin version, do you have a chance to update to the latest one?
also here is the output I can see from my dev console, can you confirm that you have the same?
![image](https://user-images.githubusercontent.com/24542698/28928853-3cac14d8-7823-11e7-9d62-cb09cafe97eb.png)

And just to double check - your update will be applied once you have restarted the app. Please let us know if it helps.

**Comment by max-mironov** [comment] 2017-08-06 21:13
Hey @siddushar, please let us know if you have a chance to look at this.

**Comment by siddushar** [comment] 2017-08-07 05:15
I pushed code-push integration to next sprit. I will Let you know once i
start working.

Thanks

**Comment by max-mironov** [comment] 2017-08-07 06:10
Ok @siddushar, got it, thanks for the response. In the meantime I believe we can close the issue currently since I was unable to reproduce it with your repro steps on Ionic2. 
Please reopen it needed when you get a chance to verify.

**Closed by max-mironov** 2017-08-07 06:10 UTC
Labels: iOS, waiting-for-clarification
