### ISSUE TITLE
Loading local files on iOS WKWebView

### ISSUE THREAD

**Issue by doender** [Microsoft/cordova-plugin-code-push#371] opened 2018-02-15 07:31 UTC
Since installing cordova-plugin-code-push, I cannot load local files (such as images, audio files, json files) anymore. This is happening on an iPhone 6S (iOS 11.2.5). Screenshot of Safari dev tools:

![image](https://user-images.githubusercontent.com/4175777/36245195-4839fe04-122a-11e8-81fc-0bf3069636d6.png)

This plugin https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix seems to solve the issue for the json files, but not for the other ones. When I uninstall cordova-plugin-code-push everything works fine again.

```
> cordova plugin ls
code-push 2.0.5 "CodePushAcquisition"
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-audioinput 0.3.0 "Audio Input"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-code-push 1.11.3 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"   
```

I'm using Ionic:
```
ionic info

cli packages:

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v9.5.0
    npm        : 2.15.12
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b
```

**Comment by iTOYS** [comment] 2018-02-15 16:17
Hi @doender 
I've noticed that you use `cordova-plugin-crosswalk-webview`
Could you please check if `code-push` works without this plugin?

Thanks!

**Comment by sithwarrior** [comment] 2018-03-12 12:51
I have the exact same problem.

If using both `cordova-plugin-ionic-webview` and `cordova-plugin-code-push` local requests, are blocked.

In my case I am using angular translate with the $translateStaticFilesLoader, for loading translations from .json files.

If both plugins are installed, the app never loads/whitescreens because the .json file cant be loaded during startup.

I tried the plugin mentioned by @doender  https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix .

This fixes loading the .json file. however, my app also uses images, camera etc. and trying to load these files gets the following error, in the safari device inspector: "**Failed to load resource: The operation couldn’t be completed. Operation not permitted**". Just as shown by @doender .

Testing this issue, I noticed that it has also been mentioned on Ionic-WKWebview
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/13

As mentioned elsewhere, everything works, if code-push is removed.

Btw. `cordova-plugin-crosswalk-webview` is a Chrome based webview for Android. It has no functionality on iOS.

**Comment by tonirilix** [comment] 2018-03-15 22:21
I'm getting the same error after installing cordova-plugin-code-push in a project that has cordova-plugin-ionic-webview installed.
After uninstalling cordova-plugin-code-push everything works fine again, but I haven't find the way to make it work with the plugin installed.

![image](https://user-images.githubusercontent.com/3756508/37492697-f26d0eae-2867-11e8-847c-055a02be8a0e.png)

**Comment by sithwarrior** [comment] 2018-03-20 09:18
I've been testing this some more, and created a starter project, with the same result.

I tried to poke around in the plugin and found the `CDVWKWebViewEngine+CodePush.m` file and found the line `#if !(TARGET_OS_SIMULATOR)`

If i switch that to say `#if (TARGET_OS_SIMULATOR)` The problem is "solved/reversed"  so it works on device, but fails on simulator.

meaning the offending code should be in this snippet

```objectivec #import "CDVWKWebViewEngine.h"

@implementation CDVWKWebViewEngine (CodePush)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-protocol-method-implementation"

- (id)loadRequest:(NSURLRequest *)request {
    NSURL *readAccessURL;
    
    // If the app is attempting to load a CodePush update, then we can lock the WebView down to
    // just the CodePush "versions" directory. This prevents non-CodePush assets from being accessible,
    // while still allowing us to navigate to a future update, as well as to the binary if a rollback is needed.
    if ([request.URL.absoluteString containsString:@"codepush"]) {
        NSString *libraryPath = NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES)[0];
        readAccessURL = [NSURL fileURLWithPathComponents:@[libraryPath, @"NoCloud", @"codepush", @"deploy", @"versions"]];
    } else {
        // In order to allow the WebView to be navigated from the app bundle to another location, we (for some
        // entirely unknown reason) need to ensure that the "read access URL" is set to the parent of the bundle
        // as opposed to the www folder, which is what the WKWebViewEngine would attempt to set it to by default.
        // If we didn't set this, then the attempt to navigate from the bundle to a CodePush update would fail.
        readAccessURL = [[[NSBundle mainBundle] bundleURL] URLByDeletingLastPathComponent];
    }
    
    return [(WKWebView*)self.engineWebView loadFileURL:request.URL allowingReadAccessToURL:readAccessURL];
}

#pragma clang diagnostic pop
```

I dont really know Objective C or the workings of the WKWebView, so Im stuck here.

We would really like to start using Code Push/Appcenter, but this is stopping us.

**Comment by sithwarrior** [comment] 2018-03-20 14:38
@iTOYS Does this still need clarification ? If so I would be happy to test anything out.

**Comment by sithwarrior** [comment] 2018-03-28 12:57
@iTOYS I've looked into this some more, and the code overwrites the loadRequest method in the Ionic WKWebView, which results in problems loading any local files on device from the webview.

I've created a PR , mostly to highlight the code in question.
#391 

With this PR, my app works smoothly with **Ionic WKWebView + CodePush** and **local files**. However, I dont know, if there are any unwanted sideeffects.

**Comment by iTOYS** [comment] 2018-03-28 13:26
Hi @sithwarrior,
Thanks for pointing!
I'll take a look on this soon

**Comment by alexandergoncharov** [comment] 2018-04-04 13:34
Hi all,

Created PR for fixing this issue: https://github.com/Microsoft/cordova-plugin-code-push/pull/396
Could you please test it?

p.s. thanks @sithwarrior for investigation


Thanks,
Alexander

**Comment by saschwarz** [comment] 2018-04-06 23:06
I couldn't successfully `cordova add` this plugin from the github repository but made the edits locally and this works for me when tested on my iOS device. Please push out a release! Thanks!

**Comment by alexandergoncharov** [comment] 2018-04-09 11:44
Hi all,

As fix already released I'll close this bug.
Please feel free to reopen bug if you have questions or issues.

Thanks,
Alexander

**Closed by alexandergoncharov** 2018-04-09 11:44 UTC
Labels: iOS, needs-investigation, prioritized, waiting-for-clarification

**Comment by gabfiocchi** [comment] 2018-04-10 12:42
Hi @alexandergoncharov,

Fix solved the problem in the simulator, but continues to happen in a real device, can you extend the fix for a device and not have to be adding another plugin that solves that?

**Comment by alexandergoncharov** [comment] 2018-04-10 12:53
Hi @gabfiocchi,

Thanks for reporting!
Hmm, it is strange. 
Could you please check your cordova-plugin-code-push version? It should be 1.11.10
You can use `cordova plugin ls`

Thanks,
Alexander

**Comment by gabfiocchi** [comment] 2018-04-10 13:16
@alexandergoncharov you're right, that dependence had not been updated, it was updated and working wonders..

Thanks!!

**Comment by Sideral-Inc** [comment] 2019-01-13 14:39
Hi,

I'm using` cordova-plugin-ionic-webview` and `cordova-plugin-code-push`. I quickly test it and it seems that I do not have local file loading issue with version 1.11.15 but I got them back with 1.11.16.

Anyone got the same issue?
