### ISSUE TITLE
Ionic - CodePush not working after version installed

### ISSUE THREAD

**Issue by manelalonso** [Microsoft/cordova-plugin-code-push#249] opened 2017-05-19 13:28 UTC
### Description

Hello, after the update is installed, it seems like CodePush is not being loaded. I don't get any errors or anything on adb logcat. The plugin just seems to be missing and sync() does nothing.
Also now i tried using the ionic plugin, but same, it installs and all good but i can't install new versions due to the fact that the function sync is not being called...

### Reproduction

- Install regular app on device
- Create new version
- Deploy it to device
- When the new version is updated and installed on device i can't install newer ones. (CodePush not loading and sync() doing nothing)

### Additional Information

* Ionic Version: 3.0.0
* iOS/Android/Windows version: Android 5.0.1
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? Real device

**Comment by max-mironov** [comment] 2017-05-22 09:06
Hello @manelalonso - thanks for reaching us.
So just to be clear - the update was not applied neither on new cordova application nor on Ionic app? Could you reproduce your issue with our [BasicSample](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic)?

Could you please share with us some code how do you bootstrap your app with CodePush?
What is shown in your deployment history?
Also is it possible for you to share with us the output of `code-push deployment history <YourAppName> <YourDeploymentName> --format json` so this way we can investigate the content being applied.

**Comment by manelalonso** [comment] 2017-05-22 12:38
Hello Max,
I'm using CodePush on Ionic, it works great with the BasicSample, but with my app it seems to be broken.

I'm implementing CodePush either two ways, first i tried like this:
`declare var codePush: any;

this.platform.ready().then(() => {
      console.log("CODEPUSH!!");
      codePush.sync();
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();

    });
`
And it works (installs the new version and everything) but when i load the app again, the new version is loaded but CodePush is not being called (codePush.sync).

The same happens if i import it with the ionic native.
`import { CodePush } from '@ionic-native/code-push';

constructor(public codepush: CodePush) {
this.platform.ready().then(() => {

      this.codepush.sync().subscribe((val) => {
        console.log(val);
      });

    })
}
`
But still happens the same...

Here i let you the output you asked me:
`[
  {
    "description": "",
    "isDisabled": false,
    "isMandatory": true,
    "rollout": null,
    "appVersion": "1.0.0",
    "packageHash": "f506d8f5de11e4d9cf6cac2dce6d143bd76b85c29fb1a55a3e214df09eaa77c6",
    "blobUrl": "https://codepush.blob.core.windows.net/storagev2/qBLgIKyEdoS6Jc5bXN-ZR-O_LAeJN1QaC4BlX",
    "size": 2397563,
    "manifestBlobUrl": "https://codepush.blob.core.windows.net/storagev2/PAmqq5u-h-HcqRs9i5wf9LfQoc4bN1QaC4BlX",
    "releaseMethod": "Upload",
    "uploadTime": 1495200247513,
    "label": "v1",
    "releasedBy": "alonsomanel@hotmail.es",
    "metrics": {
      "active": 1,
      "downloaded": 1,
      "failed": 0,
      "installed": 1,
      "totalActive": 1
    }
  },
  {
    "description": "",
    "isDisabled": false,
    "isMandatory": true,
    "rollout": 100,
    "appVersion": "1.0.0",
    "packageHash": "580bd8197a6b2b7ae138bc2a0daebc7bcb930b9c6e20b14600ab69f0e3c83cd2",
    "blobUrl": "https://codepush.blob.core.windows.net/storagev2/svcgFKX_QYfSSITrY7TsPJLjsWfuN1QaC4BlX",
    "size": 2397570,
    "manifestBlobUrl": "https://codepush.blob.core.windows.net/storagev2/rdv3YFtgchwHIR9BZ2liJyTj0ic8N1QaC4BlX",
    "releaseMethod": "Upload",
    "uploadTime": 1495200368885,
    "label": "v2",
    "releasedBy": "alonsomanel@hotmail.es",
    "diffPackageMap": {
      "f506d8f5de11e4d9cf6cac2dce6d143bd76b85c29fb1a55a3e214df09eaa77c6": {
        "size": 335187,
        "url": "https://codepush.blob.core.windows.net/storagev2/D7w8kGP6d1dfU4Fvd6zeb1Wy0eFZN1QaC4BlX"
      }
    }
  }
]
`

**Comment by max-mironov** [comment] 2017-05-22 15:05
@manelalonso 
Thanks for quick reply. So basically I've tried it with blank ionic app and seems works good to me.
My init code is the following (in app.component.ts):

```import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar, Splashscreen } from 'ionic-native';

import { HomePage } from '../pages/home/home';


declare const codePush:any


@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage = HomePage;

  constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();
      codePush.sync();
    });
  }
}
```

Also which way do you release an update? 
I've tried this: 1) run `ionic build android` to webpack updated contents && then run `code-push release-cordova <AppName> android` to upload released content to server.

So have tried it several times and it works for me. 
What do you see in developer tools console window?
E.g. my output is the following:
![image](https://cloud.githubusercontent.com/assets/24542698/26314898/420f3182-3ec4-11e7-9dac-126046e3a223.png)

**Comment by manelalonso** [comment] 2017-05-22 15:19
Thanks for your reply.
I used the same code in app.components.ts, but i release an update quite different. I use `ionic cordova build android`. Also i upload it like this `code-push release-cordova App android -m`.

The first time i launch the app (clear, just compiled to the device without versions) it updates it. As you can see here:
![image](https://cloud.githubusercontent.com/assets/12877219/26315719/546b4da4-3f12-11e7-9af4-fd6dbc7c8b19.png)

And when it is installed it loads it succesfully as you can see here:
![image](https://cloud.githubusercontent.com/assets/12877219/26315779/7f9cc61a-3f12-11e7-8e51-0f25ea49a8c0.png)

And now here's the tricky part, when i close the app and relaunch it, the version loads but the codePush.sync() function is not being executed.
![image](https://cloud.githubusercontent.com/assets/12877219/26315882/cf037b68-3f12-11e7-96b3-72ed2b9e3e39.png)

As you can see it does not even check for updates or anything... It's so strange and a bit frustrating...

**Comment by max-mironov** [comment] 2017-05-23 09:31
@manelalonso thank you for your reply, that really looks odd. So here you mean that device ready was called (even after 5427ms) but after all the subsequent code push sync calls were not executed?

To reproduce the issue I've pushed [my Ionic test project ](https://github.com/max-mironov/Ionic2-Test) to git. I've verified that updates works for me (say `code-push sync` is called each time I've restarted the app) within this app (tested on Android real device, configured wth my deployment key, please feel free reconfigure this if needed). Released updates to the app as I've described it above. 

Could you please check this example to see if the issue still occurs for you here?

**Comment by manelalonso** [comment] 2017-05-23 14:14
It works with your project. I'm going to start thinking it's some plugin fault... Here's a list of the plugins i'm using, maybe you know if some plugins are causing the trouble.

```
code-push 1.9.0-beta "CodePushAcquisition"
com.synconset.imagepicker 2.1.7 "ImagePicker"
cordova-hot-code-push-plugin 1.5.2 "Hot Code Push Plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.0 "Camera"
cordova-plugin-code-push 1.9.4-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crosswalk-webview 2.1.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.2 "File"
cordova-plugin-file-transfer 1.6.2 "File Transfer"
cordova-plugin-geolocation 2.4.2 "Geolocation"
cordova-plugin-inappbrowser 1.7.0 "InAppBrowser"
cordova-plugin-nativegeocoder 1.0.2 "NativeGeocoder"
cordova-plugin-nativestorage 2.2.1 "NativeStorage"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.2 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.3 "PushPlugin"

```

**Comment by max-mironov** [comment] 2017-05-23 14:55
@manelalonso I'm not aware if some of these plugins can cause such kind of issues, I believe I can investigate it more if you can share the reference to your app with me. 
Also I think it make sense to try to remove/add all plugins again and see if it fixed the issue. Please let us know the results.

**Comment by max-mironov** [comment] 2017-05-26 05:41
Hey @manelalonso, just wondering if you have any updates about the issue? Have you tried to remove/add plugins again to verify if it helps?

**Comment by manelalonso** [comment] 2017-05-26 06:26
Hello there, 
Sorry but I couldn't test any of this yet, probably next Monday I will test it and tell you how it's going. It's a work project and I cannot access it from home. 

Thanks for your interest.

**Comment by max-mironov** [comment] 2017-05-26 06:30
@manelalonso - no problem, keep us posted!

**Comment by manelalonso** [comment] 2017-05-26 17:17
Hello again,
I tried removing all the plugins from the project, and with no success it is not working...
Maybe we could talk on a private way so i could show you the project. Can you @max-mironov ?

**Comment by max-mironov** [comment] 2017-05-29 07:54
@manelalonso - sure thing! Please feel free to reach me via skype: `max.mironov89`, so we can discuss the details.

**Comment by max-mironov** [comment] 2017-05-30 12:32
It turns out that the issue was due to CSP Meta tag was not allowing the app to reach CDV files. 
Closing it now since the issue is fixed.

**Closed by max-mironov** 2017-05-30 12:32 UTC

**Comment by davec21** [comment] 2017-10-04 16:45
I am having the same issue as this. I am running the latest code push plugin against an Ionic Project.  The first update install works fine, however afterwards I don't seem to get beyond a status of 5.

What I am seeing is the exact error as seen by the initial report. I added the CSP line in the index.html but doesn't seem to make any difference.

**Comment by levarberry** [comment] 2017-11-03 21:13
This use to work on previous apps.. but isn't working for me either on Ionic 3  and ionic-native/code-push version 4.3.2     the Sync doesn't see to fire at all.     I am trying this on an ionic app on my phone.

**Comment by ruslan-bikkinin** [comment] 2017-11-07 07:38
@davec21 @levarberry please fill the new issue using our issue form so we be able to help you quicker.

**Comment by augustotmw** [comment] 2021-01-04 15:41
> It turns out that the issue was due to CSP Meta tag was not allowing the app to reach CDV files.
> Closing it now since the issue is fixed.

Im facing exactly the same problem here, how is this meta-tag is implemented?

**Comment by augustotmw** [comment] 2021-01-05 14:02
Hi! 😊

This solution works for me: https://github.com/ionic-team/ionic2-app-base/issues/126#issuecomment-344847012
