### ISSUE TITLE
 differential updates not working? 

### ISSUE THREAD

**Issue by aaronorosen** [Microsoft/cordova-plugin-code-push#255] opened 2017-06-09 15:21 UTC
When I push out a new update only changing a single line in a small file I notice that code-push still needs to download a lot of data. I'm wondering if perhaps the differential updates aren't working?

Each time I push out a new build if I alert totalBytes the value is always around 24Megs  (24905409). Any ideas why this is the case? 

```
  codePush.sync(syncStatus,  {installMode: InstallMode.IMMEDIATE,
                           deploymentKey: 'xxxxxx'}, function(p) {
              alert( p.totalBytes);
  });

```

**Comment by sergey-akhalkov** [comment] 2017-06-14 10:26
Hi @aaronorosen, sorry for late reply and thanks for reaching us. I can confirm that I'm experiencing the same issue, so we'll investigate and fix it. 

We'll let you know if any updates, sorry for the inconvenience.

**Comment by dongbingbin77** [comment] 2017-06-21 10:21
Meaning that this function is the default, but now there are bugs, need to repair it? If so, I would like to know when to fix this problem?

**Comment by fenglu09** [comment] 2017-06-21 12:17
I'm experiencing the same issue too. Hope solved this soon.

**Comment by fenglu09** [comment] 2017-06-22 13:14
Have  any updates about this issue?

**Comment by sergey-akhalkov** [comment] 2017-06-23 14:12
Hi @fenglu09, thanks for reaching us, we've investigated it and found out the root cause of the issue. So the fix has been implemented and we are going to test it and verify if everything is ok.
I hope that we'll deploy the fix to Prod soon (I suppose it will happen on next week). Ones again - sorry for the inconvenience and for the delay. I'll let you know if any updates.

**Comment by sergey-akhalkov** [comment] 2017-06-26 13:11
Hey guys, the fix has been deployed, please try to release new update and verify if it works for you. Feel free to reopen if needed.

**Closed by sergey-akhalkov** 2017-06-26 13:11 UTC
Labels: bug, fix-in-master
