### ISSUE TITLE
Install does not complete update from resume

### ISSUE THREAD

**Issue by chrislam** [Microsoft/cordova-plugin-code-push#137] opened 2016-06-15 03:42 UTC
Hi,

I'm having trouble getting my app to update on resume, I can see in the logs that the update is successfully identified and downloaded. The last SyncStatus I see is INSTALLING_UPDATE before some sandbox deny errors, one of which seems to be for reading the index.html file in the `codedeploy/versions` folder. Installing on restart does seem to work though.

I've setup my `config.xml` as per the instructions [here](https://github.com/Microsoft/cordova-plugin-code-push#getting-started) but maybe there is something else I need to configure as I'm using the WKWebView provided by `cordova-plugin-wkwebview-engine`?

Any help would be greatly appreciated.

Cheers

**Comment by chrislam** [comment] 2016-06-15 03:53
Just as a bit more info, using the mandatory install mode with install immediately also fails in the same way as above, downloads but then has sandbox file access errors for version index.html files.

**Comment by lostintangent** [comment] 2016-06-15 04:02
@chrislam I'm sorry to hear that you're hitting this issue. Could you share the exact error messages you're getting regarding the sandbox? That would be really useful.

Also, could you share the plugins and platforms versions your app is using by running "cordova plugin ls" and "cordova platform ls"? Thanks! We'll try to get to the bottom of this ASAP.

**Comment by lostintangent** [comment] 2016-06-15 04:10
Also, could you share which iOS version your targeting and whether it's a simulator or a device? I just want to make sure we repro this exactly as you're seeing it.

Also, if it wouldn't be too much trouble, it would be really helpful if you could try remove the wkwebview plugin and see whether it works. It's possible that we had a regression that impacted apps using that plugin. Thanks!

**Comment by chrislam** [comment] 2016-06-15 04:24
Thanks for the quick response @lostintangent, I've added the info you've requested below:

**Comment by chrislam** [comment] 2016-06-15 04:38
Thanks for the quick response @lostintangent, I've added that info below

Logs regarding the sandbox
```
Jun 15 14:09:46 iPhone <App Name> <Warning>: [CodePush] Installing update
Jun 15 14:09:48 iPhone kernel[0] <Notice>: Sandbox: <App Name> deny(1) file-issue-extension /
Jun 15 14:09:48 iPhone <App Name> <Warning>: [CodePush] Install succeeded.
Jun 15 14:09:48 iPhone kernel[0] <Notice>: Sandbox: com.apple.WebKit(19335) deny(1) file-issue-extension /private/var/mobile/Containers/Data/Application/B008DEC3-629B-4F5E-90F3-F03DA52013B0/Library/NoCloud/codepush/deploy/versions/8143a3ad93e14496dd3881fe86383576a05982c0f69573e6ab601a9673b462c4/www/index.html
Jun 15 14:09:48 iPhone kernel[0] <Notice>: Sandbox: com.apple.WebKit(19334) deny(1) file-read-data /private/var/mobile/Containers/Data/Application/B008DEC3-629B-4F5E-90F3-F03DA52013B0/Library/NoCloud/codepush/deploy/versions/8143a3ad93e14496dd3881fe86383576a05982c0f69573e6ab601a9673b462c4/www/index.html
```

```
❯ cordova plugin ls
code-push 1.9.0-beta "CodePushAcquisition"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-custom-config 2.0.0 "cordova-custom-config"
cordova-plugin-code-push 1.8.0-beta "CodePush"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-crosswalk-webview 1.7.2 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.0.3 "Cordova WKWebView Engine"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
phonegap-plugin-push 1.6.0 "PushPlugin"
```

```
❯ cordova platform ls
Installed platforms:
  android 5.1.1
  browser 4.1.0
  ios 4.1.1
```

We're currently targeting iOS 8.0 when building but I'm testing on a iOS 9.3.2 iPhone 6. I'll try removing the WKWebView plugin and report back with my findings. Cheers!

**Comment by chrislam** [comment] 2016-06-15 04:55
My testing without the `wkwebview-engine` plugin was successful, the update installs without sandbox errors and then restarts when the app is next resumed. When using a mandatory update, the app is restarted immediately as expected.

**Comment by lostintangent** [comment] 2016-06-15 05:01
OK perfect, that helps narrow down the issue a ton. We did work to make the WKWebView work with our plugin, so something must have regressed. We'll look into this ASAP. Thanks so much for helping capture this repro and providing the feedback.

**Comment by lostintangent** [comment] 2016-06-16 21:13
@chrislam OK I figured out the issue and the fix. I'll be sending out a PR very shortly. It would be great if you had some time to help validate it is possible.

**Comment by chrislam** [comment] 2016-06-16 21:21
@lostintangent awesome! I'll check it out straight away.

**Comment by lostintangent** [comment] 2016-06-17 00:40
@chrislam If you get a chance, and can install the bits from the linked PR, that would be awesome. I did a bunch of testing, but I'd also love to have you validate it.

**Comment by chrislam** [comment] 2016-06-17 00:49
@lostintangent we've done a bit of testing here and it all looks good, thanks!

**Comment by lostintangent** [comment] 2016-06-17 00:52
@chrislam Yay! That you so much for the confirmation. Once I get a couple more sign offs, I'll merge this and we can release an update to NPM tomorrow.

**Comment by chrislam** [comment] 2016-06-17 02:18
Hi again @lostintangent sorry to say but after further testing seems like I still have an issue here, specifically I'm trying to use a mandatory update which should be applied on the very first boot of the app so I can't wait for the OS or the user to restart the app.

**Comment by lostintangent** [comment] 2016-06-17 02:22
Are you still seeing the sandbox errors in the console when the app is trying to restart? The mandatory update shouldn't be any different than the resume-based install you were trying, since they're both forcing a programmatic restart.

**Comment by chrislam** [comment] 2016-06-17 02:32
Yes still seeing them, the test I just ran gave these two after I first installed a base build to my phone (did not run it yet), made a small text change to my app, rebuilt my app, made a mandatory Code Push release and then ran the app. 
```
Jun 17 14:24:39 iPhone App Name[21285] <Warning>: [CodePush] Install succeeded.
Jun 17 14:24:39 iPhone App Name[21285] <Warning>: SyncStatus 1
Jun 17 14:24:39 iPhone kernel[0] <Notice>: Sandbox: com.apple.WebKit(21287) deny(1) file-issue-extension /private/var/mobile/Containers/Data/Application/BA5A90E4-E3F7-41EF-AA68-D99D69500C02/Library/NoCloud/codepush/deploy/versions/4dbcef1a2e3969252be42ed1d5e61ebf9530ed3a600750fc2b15dca3cba8322a/www/index.html
Jun 17 14:24:39 iPhone kernel[0] <Notice>: Sandbox: com.apple.WebKit(21286) deny(1) file-read-data /private/var/mobile/Containers/Data/Application/BA5A90E4-E3F7-41EF-AA68-D99D69500C02/Library/NoCloud/codepush/deploy/versions/4dbcef1a2e3969252be42ed1d5e61ebf9530ed3a600750fc2b15dca3cba8322a/www/index.html
```
I do note that I'm seeing a Install succeeded that I wasn't before.

**Comment by lostintangent** [comment] 2016-06-17 03:15
Just to confirm, are you testing the fix by installing via "cordova plugin add https://github.com/Microsoft/cordova-plugin-code-push#b901b1afd5a49e6976ff515875790c411e0bdb3d"?

**Comment by chrislam** [comment] 2016-06-17 03:24
Yup that's the one

**Comment by chrislam** [comment] 2016-06-17 08:18
I found this fix for a similar issue in a different plugin which I've successfully tested https://github.com/nordnet/cordova-hot-code-push/commit/dcf8c6fc6ce58a2ff91b9444890c752410e0ec42 is there a way to do something similar here?

The concept is that WKWebView restricts access to the file it's loading if the request URL is a file i.e. `www/index.html` and won't let it's target be changed but if the target is a directory then any file in the file structure below that target can be targeted without a new WKWebView being created.

**Comment by lostintangent** [comment] 2016-06-17 18:30
This got auto-closed by my PR. @chrislam I'm investigating the fix you mentioned above, thanks for the pointer!

**Comment by lostintangent** [comment] 2016-06-18 00:19
@chrislam If you get a chance, I would love to get your validation for #145.

**Comment by chrislam** [comment] 2016-06-18 02:37
@lostintangent yeah that's working great, thanks for all your help on this! It's very much appreciated!

**Comment by lostintangent** [comment] 2016-06-18 03:28
Awesome. Thanks again for your patience and help validating my fixes.

**Comment by lostintangent** [comment] 2016-06-19 17:02
This has been released to NPM! Let us know if you run into any other issues.

**Closed by lostintangent** 2016-06-19 17:02 UTC
