### ISSUE TITLE
Met the "Cannot perform diff-update." error for Android

### ISSUE THREAD

**Issue by chineseneo** [Microsoft/cordova-plugin-code-push#199] opened 2016-12-13 01:37 UTC
These days I have run into a "Cannot perform diff-update." for my android application based on cordova.

After debug I found out that the error is firstly generated in the copyDirectoryEntriesTo function of fileUtil.js. While copying each entry in the src directory, the program will meet some entries which could cause a code:1 error during copy, which is a file not found error: `FileError.NOT_FOUND_ERR = 1;`. 

In my case, the error entries are: `.DS_Store` files (because I am using mac) and empty folders in the plugins directory (because I was removing some cordova plugins).

So After check my `platforms/android/assets/www` directory for `.DS_Store` files and empty directories, I removed those entries and then my application is good to upgrade with code-push.

I don't know yet why there could be such `file not found error`, since the .DS_Store file and directory do exist. For temporary solution I will remove these exception entries every time before a make a package. But maybe there is a better and robust solution for this?

**Comment by vladimir-kotikov** [comment] 2016-12-16 07:36
@chineseneo could you please provide some additional details, specifically versions of cordova, cordova-android and installed plugins? You can get these by running `cordova -v && cordova platform ls && cordova plugin ls` in you project directory.

**Comment by chineseneo** [comment] 2016-12-16 07:51
@vladimir-kotikov here is the information:

```
5.4.1
Installed platforms: android 4.1.1, ios 3.9.2
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, osx, webos
TalkingData 1.2.24 "TalkingData"
code-push 1.9.0-beta "CodePushAcquisition"
com.develcode.plugins.volumeControl 1.0 "Android Volume Control Plugin"
com.hutchind.cordova.plugins.streamingmedia 0.1.4 "StreamingMedia"
com.neton.cordova.diagnostic 0.2.3 "Diagnostic"
com.qdc.plugins.baidu.location 1.0.0 "BaiduLocation"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
com.wg.tronclass.player 0.1.0 "Player"
com.xmartlabs.cordova.market 1.1 "Market"
cordova-plugin-android-support-v4 21.0.1 "Android Support v4"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-chrome-apps-system-cpu 1.1.2-dev "Chrome System CPU API"
cordova-plugin-code-push 1.9.2-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-crosswalk-webview 1.6.1 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-dialogs 1.3.0 "Notification"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-file-opener2 2.0.2 "File Opener2"
cordova-plugin-file-transfer 1.5.2-dev "File Transfer"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-globalization 1.0.3 "Globalization"
cordova-plugin-inappbrowser 1.5.1-dev "InAppBrowser"
cordova-plugin-native-transitions 0.2.3 "Native Transitions"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-qqsdk 0.3.9 "YCQQ"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-transport-security 0.1.2 "App Transport Security"
cordova-plugin-wechat 1.1.3 "Wechat"
cordova-plugin-weibosdk 0.3.4 "YCWeibo"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-volume-control 1 "VolumeControl"
de.appplant.cordova.common.registerusernotificationsettings 1.0.1 "RegisterUserNotificationSettings"
ionic-plugin-keyboard 2.0.1 "Keyboard"
jpush-phonegap-plugin 2.2.5 "JPush Plugin"
net.yoik.cordova.plugins.screenorientation 1.4.0 "Screen Orientation"
phonegap-plugin-barcodescanner 6.0.1 "BarcodeScanner"
```

**Comment by sergey-akhalkov** [comment] 2016-12-19 09:33
@chineseneo, unfortunately, we are not able to reproduce provided issue with the specified environment information and following repro steps:
1. We've created default "myapp" cordova project with code-push plugin
2. Changed cordova-plugin-file and cordova-plugin-file-transfer versions to 3.0.0 and 1.5.1 respectively
3. Deployed myapp to android emulator.
4. Added empty "cordova-plugin-empty" folder to myapp/www/plugins folder
5. Changed content of myapp/www/index.html file.
6. Executed "code-push release-cordova myapp android" command (after this "cordova-plugin-empty" folder was appeared in myapp/platform/android/assests/www/plugins folder)
7. Then we've launched myapp on android emulator and install updates with code-push plugin without any errors.

So could you please correct our repro steps or provide us with yours so we would able to reproduce and fix this issue?

**Comment by chineseneo** [comment] 2016-12-19 10:00
@sergey-akhalkov hi, thanks for the efforts. I think the problem could be more possibly existing on the package stage. I mean, when code-push is performing a diff update, it will scan local package, and if it didn't find one, it will copy everything from the assets/www folder to some folder under /data/data. My problem occurred when it is copying those files. So a more possible way of regenerating this issue is to place an empty folder in www/plugins before you package the app, and then deploy it and do the update.

**Comment by sergey-akhalkov** [comment] 2016-12-20 08:06
@chineseneo, hi, thanks for the correction. Before step 3 (Deployed `myapp` to android emulator) I've added several empty folders into `myapp/www/plugins` folder and 1 empty folder directly into `myapp/www`. Then I've repeated steps 4-7 and received no errors. Seems like this issue is rare and has more complex root.  I'll continue investigation, but I'll be grateful if you could provide a minimal app where bug reproduces.

**Comment by elliotstokes** [comment] 2017-01-12 12:09
I'm just in the process of setting up code-push anad am also seeing 

```
[CodePush]  Cannot perform diff-update.
plugins/cordova-plugin-code-push/bin/www/codePushUtil.js:40 
[CodePush] An error occurred during sync.
```

Ill try the removal of .DS_Store files to see if this fixes things.

**Comment by chineseneo** [comment] 2017-01-13 02:06
@elliotstokes please also remove empty directories if any.

**Comment by sergey-akhalkov** [comment] 2017-01-13 11:17
@elliotstokes, @chineseneo - hi!
I've also reproduced this issue and found out, that the issue occurs while trying to open `/localhost/assets/www/.DS_Store` file.
`CordovaResourceApi.java`:
```
                try {
                    assetFd = assetManager.openFd(assetPath); //   "www/.DS_Store"
                    inputStream = assetFd.createInputStream();
                    length = assetFd.getLength();
                } catch (FileNotFoundException e) {
                    // Will occur if the file is compressed.
                    inputStream = assetManager.open(assetPath);
                }
                String mimeType = getMimeTypeFromPath(assetPath);
                return new OpenForReadResult(uri, inputStream, mimeType, length, assetFd);
```
I've also found this https://github.com/apache/cordova-plugin-file/pull/189 PR fixing the same issue, so you could try to copy this https://github.com/mnill/cordova-plugin-file/blob/2c43a1b43ffff2d3ab5a837e997c81b4708a76d3/src/android/build-extras.gradle file into `platfroms/android/` directory. I'm not sure about empty directories, but patched `build-extras.gradle` file helps me to avoid `DS_Store` files problem.

**Comment by chineseneo** [comment] 2017-01-17 07:56
@sergey-akhalkov thanks for the efforts and information :)

**Comment by beck24** [comment] 2017-01-20 13:44
I'm also experiencing the same thing, though no .DS_Store files are to be found so I'm not sure that's the root cause

```cordova -v && cordova platform ls && cordova plugin ls
6.2.0
Installed platforms:
  android 5.1.1
  browser 4.1.0
  ios 4.1.1
Available platforms:
  amazon-fireos ~3.6.3 (deprecated)
  blackberry10 ~3.8.0
  firefoxos ~3.6.3
  osx ~4.0.1
  webos ~3.7.0
code-push 1.9.0-beta "CodePushAcquisition"
cordova-plugin-admobpro 2.24.0 "AdMob Plugin Pro"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-code-push 1.9.2-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crosswalk-webview 2.1.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.1 "Notification"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-google-analytics 1.7.4 "Google Universal Analytics Plugin"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.1-dev "Cordova WKWebView Engine"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.0 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.0.10 "OneSignal Push Notifications"```

**Comment by sergey-akhalkov** [comment] 2017-01-20 14:40
@beck24 - hi! The last time I've tried to determine the cause of the issue I've dived deep inside Cordova java files and figured out that the cause of the issue is in `assetManager.openFd` java method :) 
So could you please help me to investigated the cause of the issue?

Here is `localPackages.js` file content:
```javascript
if (error || currentPackageError || cleanDeployError) {
    handleError(new Error("Cannot perform diff-update."));
} else {
```
As we can see there are 3 possible causes of the issue, at first, we should figure out which error triggers the exception. So please put this line `console.log(error, currentPackageError, cleanDeployError);`  before `handleError(new Error("Cannot perform diff-update."));`. Provided output will allow us to continue investigation.

**Comment by beck24** [comment] 2017-01-20 21:03
Awesome, will do that this evening and hopefully we can track it down.

**Comment by beck24** [comment] 2017-01-21 09:08
I tried reinstalling the plugins just-in-case, and I logged a few things on the initial test of this and found that it's trying to update from a very old version:

    RemotePackage {appVersion: "0.0.3", deploymentKey: "my-deployment-key", description: "", downloadUrl: "https://codepushupdates.azureedge.net/storagev2/<some-hash>", isMandatory: false, label: "v11", packageHash: "<hash>", packageSize: 1984172}

while if I look at the most recent package:

    code-push deployment list wtm-android
    ┌────────────┬─────────────────────────────────────┬──────────────────────┐
    │ Name       │ Update Metadata                     │ Install Metrics      │
    ├────────────┼─────────────────────────────────────┼──────────────────────┤
    │ Production │ No updates released                 │ No installs recorded │
    ├────────────┼─────────────────────────────────────┼──────────────────────┤
    │ Staging    │ Label: v15                          │ No installs recorded │
    │            │ App Version: 0.0.6                  │                      │
    │            │ Mandatory: No                       │                      │
    │            │ Release Time: 25 minutes ago        │                      │
    │            │ Released By: my-email-address       │                      │
    │            │ Description: trivial code-push test │                      │
    └────────────┴─────────────────────────────────────┴──────────────────────┘

Seems clear to me that it would fail if it tried to apply a package older than what is already currently installed.  Is it something I did wrong in the workflow?
I'll still try to get those other values for you here...

**Comment by beck24** [comment] 2017-01-21 09:33
alright, I've tried it again, this time with the modified localPackage.js

Here's my workflow, in case you see anything I'm doing wrong to cause this.

1. version bump my app in config.xml to 0.0.7 and load it onto my test device via usb
```ionic run android --prod```
1. Force close the app
1. make a trivial change to the app (a few characters in static html) and push a new change
```ionic build android --prod```
```code-push release-cordova wtm-android android -d Staging -t "0.0.7" --description "trivial code-push test"```
1. check the version in code-push
```code-push deployment list wtm-android```
┌────────────┬─────────────────────────────────────┬──────────────────────┐
│ Name       │ Update Metadata                     │ Install Metrics      │
├────────────┼─────────────────────────────────────┼──────────────────────┤
│ Production │ No updates released                 │ No installs recorded │
├────────────┼─────────────────────────────────────┼──────────────────────┤
│ Staging    │ Label: v16                          │ No installs recorded │
│            │ App Version: 0.0.7                  │                      │
│            │ Mandatory: No                       │                      │
│            │ Release Time: a few seconds ago          │                      │
│            │ Released By: my-email       │                      │
│            │ Description: trivial code-push test │                      │
└────────────┴─────────────────────────────────────┴──────────────────────┘

1. Open the app on the device - will trigger the update check, while inspecting in chrome console

Inspecting the console I see that it is trying to install the same old remote package as in my previous comment for app version 0.0.3.
I tap install anyway so we can play this out and this is the console output for those 3 variables.
![screen shot 2017-01-21 at 1 24 06 am](https://cloud.githubusercontent.com/assets/738363/22173469/293ea142-df79-11e6-8d92-757e4953c85c.png)

So it is the ```currentPackageError```
However I think the root cause is CodePush.checkForUpdate() returning the wrong package info, though I'm not counting out a workflow error on my part for that, this is still new territory for me.

**Comment by beck24** [comment] 2017-01-23 09:14
Looks like this might be a symptom of this: https://github.com/Microsoft/cordova-plugin-code-push/issues/196

**Comment by sergey-akhalkov** [comment] 2017-01-23 10:26
@beck24, yeah, probably it is. So could you please apply https://github.com/Microsoft/cordova-plugin-code-push/pull/202 and https://github.com/Microsoft/cordova-plugin-code-push/pull/201 PRs and let me know if the issue is still reproduces?

**Comment by beck24** [comment] 2017-01-26 09:06
I haven't forgotten about this - but in the meantime I was working with some other plugins and got my code in a bit of an unstable state.  Will test those PRs as soon as I get back to a stable state.  This is just a personal side-project though so it's not happening super quickly, sorry.

**Comment by sergey-akhalkov** [comment] 2017-01-26 10:32
@beck24, no problem!

**Comment by beck24** [comment] 2017-01-28 10:26
@sergey-akhalkov 

My apologies for the wait, but I've been able to apply those PRs locally and test it out and I can confirm that those changes resolve my issue.  Please get those merged in asap 👍

**Comment by sergey-akhalkov** [comment] 2017-01-30 08:40
@beck24, got it, thanks!

**Closed** 2017-02-15 06:56 UTC

**Comment by amjadyahya** [comment] 2017-08-12 10:36
the 'skip “.DS_Store” and “__MACOSX” entries while copying' has been added to the fileUtil.ts but not to the fileUtil.js in the official repo

**Comment by max-mironov** [comment] 2017-08-14 10:57
Hey @amjadyahya - thanks for pointing at this!
Synced js part with latest TS changes (https://github.com/Microsoft/cordova-plugin-code-push/pull/279)

**Comment by nshoes** [comment] 2019-04-17 18:34
Sorry to ressurrect an old issue, but I'm hitting a similar issue on Android right now:

```
[CodePush] Cannot perform diff-update.. StackTrace: Error: Cannot perform diff-update. at file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/localPackage.js:360:37 at FileReader.fileReader.onloadend (file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/fileUtil.js:232:17) at FileReader.readSuccessCallback (file:///android_asset/www/plugins/cordova-plugin-file/www/FileReader.js:164:18) at Object.callbackFromNative (file:///android_asset/www/cordova.js:291:58) at <anonymous>:1:9
```

Cordova@8.1.2, plugins:
```
branch-cordova-sdk 3.1.5 "branch-cordova-sdk"
code-push 2.0.6 "CodePushAcquisition"
cordova-plugin-appcenter-analytics 0.3.3 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.3.3 "App Center Crashes for Cordova"
cordova-plugin-appcenter-push 0.3.3 "App Center Push for Cordova"
cordova-plugin-appcenter-shared 0.3.3 "App Center shared code for Cordova"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-code-push 1.11.17 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-vibration 2.1.6 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.5-dev "Cordova WKWebView Engine"
cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
skwas-cordova-plugin-datetimepicker 1.1.3 "DateTime picker"
```
