### ISSUE TITLE
Error Status 503, Service unavailable on checking for update

### ISSUE THREAD

**Issue by pitAlex** [Microsoft/cordova-plugin-code-push#272] opened 2017-07-23 10:57 UTC
Hello,

As the name says we recently started getting 503 error on checking for updates in iOS. Is this related to code-push being moved to Mobile Center? The issue has been going on for 2 days now.

**Comment by sergey-akhalkov** [comment] 2017-07-24 10:02
Hi @pitAlex, thanks for reaching us. I've looked for logs with 503 responses on CodePush server, but I can see no such kind of responses. 

Does the issue is still reproduced?

**Comment by pitAlex** [comment] 2017-07-24 10:12
In our tests the app works, however for our users, our sentry keeps sending this message. Could it be a cache thing? I know iOS does this sometimes

**Comment by sergey-akhalkov** [comment] 2017-07-24 10:39
>In our tests the app works, however for our users, our sentry keeps sending this message.

It is weird, but I believe we should receive a lot of requests from customers which similar with ours in case the issue relates to CodePush service.

>Could it be a cache thing? I know iOS does this sometimes

I don't think so, but you could try reinstall your app and verify if the issue is still reproduced, also you could provide us with the minimal version of your app where the issue is reproduced - so we'll take a look if the issue is reproduced for us and instigate/fix it.

**Comment by pitAlex** [comment] 2017-07-24 11:40
Sure, here is how we currently handle it:

```
// custom event polyfill
(function () {
    
    if(!window.top.CustomEvent) {
        var CustomEvent = function (event, params) {
            var evt, origPrevent;
            params = params || {
                bubbles: false,
                cancelable: false,
                detail: undefined
            };

            evt = window.top.document.createEvent("CustomEvent");
            evt.initCustomEvent(event, params.bubbles, params.cancelable, params.detail);
            origPrevent = evt.preventDefault;
            evt.preventDefault = function () {
                origPrevent.call(this);
                try {
                    Object.defineProperty(this, 'defaultPrevented', {
                        get: function () {
                            return true;
                        }
                    });
                } catch (e) {
                    this.defaultPrevented = true;
                }
            };
            return evt;
        };

        CustomEvent.prototype = window.top.Event.prototype;
        window.top.CustomEvent = CustomEvent; // expose definition to window
    }
})();


var codePushWrapper = window.top.codePush;

codePushWrapper.checkForUpdate(function (pack) {
    // - wrap the code-push sync into a function so it can be retried
    var syncFunc = function (mandatory, retried) {
        codePushWrapper.sync(function (status) {
            // -- retry once if something went wrong on downloading/installing updates
            if (status == window.top.SyncStatus.ERROR) {
                if (!retried) {
                    setTimeout(function () {
                        syncFunc(mandatory, true);
                    }, 10);
                }
                else {

                    customEventBroadcast('$updates:failed', { code: null, error: 'updates downloading/installing' });
                }
            }
            else if (status == window.top.SyncStatus.UPDATE_INSTALLED) {
                customEventBroadcast('$updates:installed');

            } else if (status == window.top.SyncStatus.UP_TO_DATE) {
                customEventBroadcast('$updates:none');
            } else if (status == window.top.SyncStatus.INSTALLING_UPDATE) {
                customEventBroadcast('$updates:installing');
            }

        }, {
                deploymentKey: key,
                installMode: window.top.InstallMode.ON_NEXT_RESTART
            }, function (progress) {

                var perc = Math.round((progress.receivedBytes * 100 / progress.totalBytes) * 100) / 100;
                customEventBroadcast('$updates:download', { percentage: perc });

            });
    };

    if (!pack) {
        customEventBroadcast('$updates:none');
    } else {
        var miniumversion = pack.appVersion;
        var mandatory = pack.isMandatory;

        if (!miniumversion) {
            customEventBroadcast('$updates:none');
        } else if (pack.failedInstall) {
            customEventBroadcast('$updates:failed', { code: 1, error: 'rolledback', details: pack.label });
        } else {
            syncFunc(mandatory);
        }
    }
}, function (error) {

    // - retry once if something went wrong on checking for updates
    if (!retried) {
        codePushCheck(true);
    }
    else {
    // - this is where were keep getting sentry logs about updates checking failed with 503 status
        customEventBroadcast('$updates:failed', { code: 0, error: 'updates checking', details: error.message });
    }
}, key);

// the sentry logger:
window.top.document.addEventListener('$updates:failed', function (event) {
    Raven.captureMessage('Native App Updater failed on :' + event.detail.error, {
        level: 'error',
        extra: {
            error: event.detail
        }
    });
}, false);
```

From the above we keep getting this log:
```
{
    code: 0,
        details: 
    `503: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
            <HTML><HEAD><TITLE>Service Unavailable</TITLE>
                <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
                <BODY><h2>Service Unavailable</h2>
                    <hr><p>HTTP Error 503. The service is unavailable.</p>
    </BODY></HTML>`, 
    error: 'updates checking'
}

```
It started happening over the weekend and we haven't done any app updates in the last 17 days.

**Comment by sergey-akhalkov** [comment] 2017-07-24 14:42
@pitAlex, thank you for providing the source codes, we'll investigate it and let you know if the issue reproduced for us or not.

**Comment by nevech** [comment] 2017-07-24 16:20
I have the same problem on android

**Comment by nevech** [comment] 2017-07-24 16:48
This problem happened when request was sent from mobile app.
If open link  https://codepush.azurewebsites.net/updateCheck?deploymentKey=xxx&isCompanion=false&label=&clientUniqueId=xxx in browser, all works.

I think problem with some headers. Probably back-end side can't find some headers.

**Comment by pitAlex** [comment] 2017-07-24 17:31
@nevech, it happens in android for us too. And I saw that on the browser the url works as well, however what I did notice in android is that a couple of times it responded with a **500** error and on retries it worked. Unfortunately the **503** is now happening intermittently on android as well.

**Comment by sergey-akhalkov** [comment] 2017-07-25 06:38
Hi @pitAlex, @nevech, we've and found out the root cause of the issue and it should work now, please verify and let us know if it still reproduced. Thank you for the patience and sorry for the inconvenience.

**Comment by pitAlex** [comment] 2017-07-25 08:33
Thank you @sergey-akhalkov. Things seems to work now, the errors have stopped. We will monitor to make sure.

**Comment by sergey-akhalkov** [comment] 2017-07-25 09:22
Hi @pitAlex, thanks for the update. So closing this for now, please feel free to reopen the issue if needed.

**Closed by sergey-akhalkov** 2017-07-25 09:22 UTC
Labels: bug, fix-in-master
