### ISSUE TITLE
File path issues -- 404 File not found after code push update

### ISSUE THREAD

**Issue by fignuts** [Microsoft/cordova-plugin-code-push#192] opened 2016-11-26 01:01 UTC
I build my app with webpack. It outputs an index.html with references to files with hashes such as "/android_asset/www/app_9d5f5138836a2af367a9.js". All of these files go into the cordova www directory. Deployed from the app store my app works fine. After a code push my javascript files are no longer found as if they are in the wrong paths. The correct files are in the cordova project when I run code-push release-cordova.

Here is the console output on a device attempting to download the code-push update:
```
codePushUtil.js:36 [CodePush] Checking for update.
codePushUtil.js:36 [CodePush] An update is available. {"appVersion":"0.4.1","deploymentKey":"p2nzibqM9wRDDCK0-Hw4bPFBlprhEJg2U5F-M","description":"","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/ejupsUIUOBnZ2gjSDbjbRRHtgmr8EJg2U5F-M","isMandatory":true,"label":"v6","packageHash":"e065afed3d83d31885c261eff60dedcc2257b3aef5e034aa9b1cb290a6c48fcf","packageSize":1154725,"failedInstall":false}
codePushUtil.js:36 [CodePush] Downloading update
Navigated to file:///data/user/0/com.taskheronative/files/codepush/deploy/versions/e065afed3d83d31885c261eff60dedcc2257b3aef5e034aa9b1cb290a6c48fcf/www/index.html
codePushUtil.js:36 [CodePush] Package download success: {"deploymentKey":"p2nzibqM9wRDDCK0-Hw4bPFBlprhEJg2U5F-M","description":"","label":"v6","appVersion":"0.4.1","isMandatory":true,"packageHash":"e065afed3d83d31885c261eff60dedcc2257b3aef5e034aa9b1cb290a6c48fcf","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
codePushUtil.js:36 [CodePush] Installing update
codePushUtil.js:36 [CodePush] Install succeeded.
index.html:119 GET file:///android_asset/www/app_9d5f5138836a2af367a9.js?9a0cd722889fab1331c8 404 (Not Found)
```

The correct file, app_9d5f5138836a2af367a9.js is in the .\cordova\platforms\android\assets\www directory after running code-push release-cordova but for some reason the cordova app is unable to find the file after code-push downloads the update. Code push correctly updates index.html but my js files can no longer be found as if code-push never delivered them or put them in the wrong directory.

**Comment by fignuts** [comment] 2016-11-26 01:10
If I download the zip from the downloadUrl above the file app_9d5f5138836a2af367a9.js is in there so I don't understand why the app can't find it.

**Comment by fignuts** [comment] 2016-11-26 21:04
It appears that CodePush does not put the new app files into /android_asset/www. Instead they are at a path like this:

`file:///data/user/0/com.taskheronative/files/codepush/deploy/versions/9438cde1ea8e0adde977ad772405a82a5af6c4db2abc86f2a25938e366c94034/www/index.html`

This means that my app can't be built with the publicPath option of webpack set to an absolute path such as '/android_asset/www'. 

Setting publicPath to './' or simply blank gives me relative references to my files but it only partially works. When webpack goes to download a new chunk at runtime it fails to find the file. Webpack inserts a script tag like this:

`<script type="text/javascript" charset="utf-8" async="" src="1_f53cdb42cb35266bfd5b.js"></script>`

but for some reason the file is not found even though it is part of the CodePush bundle. This seems to be happening for some of my images referenced via webpack require() as well.

**Comment by sergey-akhalkov** [comment] 2017-03-10 12:34
@fignuts, sorry for the late reply.
>It appears that CodePush does not put the new app files into /android_asset/www. Instead they are at a path like this:
file:///data/user/0/com.taskheronative/files/codepush/deploy/versions/9438cde1ea8e0adde977ad772405a82a5af6c4db2abc86f2a25938e366c94034/www/index.html

That is correct behavior. CodePush creates new folder that contains all source codes files. That happens each time CodePush plugin receives new update from the CodePush servers. 

That's the root cause why you have to use relative paths.

Please let me know if you have any questions.

**Comment by sergey-akhalkov** [comment] 2017-03-21 08:58
Closing this for now, please feel free to reopen if you see any issues or have any questions.

**Closed by sergey-akhalkov** 2017-03-21 08:58 UTC
Labels: investigating

**Comment by fignuts** [comment] 2017-05-23 20:59
Still struggling with this. My ```.\cordova\platforms\android\assets\www``` folder contains ```2bb8ddc2c2c5db81a8962f6efd02e85c.png``` however after a code push  ```<img src="2bb8ddc2c2c5db81a8962f6efd02e85c.png" />``` comes back as file not found. It seems like code push is leaving files out of my project?

**Comment by fignuts** [comment] 2017-05-23 22:50
@sergey-akhalkov I have discovered something else strange. Images which are *not* rendered by React show up just fine. ```<img src="2bb8ddc2c2c5db81a8962f6efd02e85c.png" />``` will fail with  ```file:///2bb8ddc2c2c5db81a8962f6efd02e85c.png Failed to load resource: net::ERR_FILE_NOT_FOUND``` when rendered via react. When the exact same HTML is in my wrapper template outside of the react portion of my app it works perfectly, referencing ```file:///data/user/0/com.taskheronative/files/codepush/deploy/versions/30be0fce0c12fd02b83c2a6d37fd2aa022f4a4f3ce389043272479d6aa51db86/www/2bb8ddc2c2c5db81a8962f6efd02e85c.png```

**Comment by fignuts** [comment] 2017-05-24 12:50
I really can't tell whether this is a code-push issue, a webpack issue, or a cordova issue. I ended up working around it by setting webpack's ```__webpack_public_path__``` to the full path of the current deployment. This seems like it is probably a fragile solution but it is the only way I could get it to work.

```

document.addEventListener("deviceready",function(){
    codePush.getCurrentPackage((packageInfo) => {
        if(packageInfo){
            let asset_path = cordova.file.dataDirectory
            asset_path += 'codepush/deploy/versions/'
            asset_path += packageInfo.packageHash
            asset_path += '/www/'
            console.log("asset path? ", asset_path)
            __webpack_public_path__ = asset_path
        } else {
            console.log("no asset path")
            __webpack_public_path__ = cordova.file.applicationStorageDirectory + '/www'
        }
        //now that we have __webpack_public_path__ set we can start the app
        require('./index.js')
    })
},false);
```

**Comment by sergey-akhalkov** [comment] 2017-05-24 13:50
Hi @fignuts, thanks for the clarification, it seems like webpack issue/preferences, because CodePush just uses [start page](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/src/android/CodePush.java#L398) as an entry point, so start page and its dependencies should use relative paths to map to installed CodePush update directory instead of apk assets dir.
So if I get it right you've specified start page (`__webpack_public_path__ `) manually by using packageInfo.packageHash value, due to webpack does not know anything about new assets location (CodePush update location)
Please let me if you have any questions of if you have any ideas/advises how we could fix the issue.
