### ISSUE TITLE
encounter "[CodePush]An Error occurred during sync." but not detailed error information.

### ISSUE THREAD

**Issue by zjx** [Microsoft/cordova-plugin-code-push#328] opened 2017-11-27 09:08 UTC
### Description

encounter the below error on iOS platform when invoke the sync function.

[16:55:51]  console.log: platform ready...
[16:55:51]  console.log: 5
[16:55:51]  console.log: [CodePush] Checking for update.
[16:55:51]  console.error: [CodePush] 0:
[16:55:51]  console.error: [CodePush] An error occurred during sync.

### Reproduction

1.  ionic start MyApp blank
2. ionic cordova plugin add cordova-plugin-code-push
3. npm install --save @ionic-native/code-push
4. modify the config.xml to add the code push deployment keys
5. add the CodePush dependencies
6. add the below code :
`
    this.platform.ready().then(() => {

    	console.log('platform ready...');

		//test 1
		const downloadProgress = (progress) => { console.log(`Downloaded ${progress.receivedBytes} of ${progress.totalBytes}`); }
		this.codePush.sync({updateDialog: true, 
			installMode:InstallMode.IMMEDIATE, 
			mandatoryInstallMode: InstallMode.IMMEDIATE},
			downloadProgress).subscribe((syncStatus) => console.log(syncStatus));
}
`
7. ionic cordova platform add ios
8. ionic cordova prepare
9. ionic cordova run iOS -- device

### Additional Information

* cordova-plugin-code-push version: 
1.10.0-beta

* List of installed plugins:
code-push 2.0.1-beta "CodePushAcquisition"
cordova-plugin-code-push 1.10.0-beta "CodePush"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-keyboard 2.2.1 "Keyboard"

* Cordova version:
7.1.0

* iOS/Android/Windows version:
iOS 11.1

* Does this reproduce on a debug build or release build? 
Both

* Does this reproduce on a simulator, or only on a physical device?
Both

* ionic version:
3.18.0

* node version:
v 8.9.1

* npm version
5.5.1

**Comment by ruslan-bikkinin** [comment] 2017-12-21 13:47
Hi @zjx and sorry for delayed response. Could you please share with us minimum version of client side code (`www` directory) so we could try to reproduce your issue on our side? Information you provided on 6 step isn't enough to identify the source of your problem.

**Comment by ruslan-bikkinin** [comment] 2017-12-26 13:31
Hi @zjx again, after further investigation I was able to reproduce your issue using the following steps:
1. Create blank ionic application.
2. Install cordova-plugin-code-push using [these instructions](https://ionicframework.com/docs/native/code-push/#installation).
3. Configure valid `CodePushDeploymentKey` in `config.xml`.
4. Add client code for code-push usage as proposed [here](https://ionicframework.com/docs/native/code-push/#usage).
5. **Disable internet for device or simulator where you are going to deploy app.**
5. Remove app from device or simulator if it was previously installed.
6. Deploy app and run it.

Could you please confirm that these repro steps match yours?

**Comment by ruslan-bikkinin** [comment] 2017-12-27 09:05
As addition to previous message:
Under the hood the issue was occured because XmlHttpRequest we are using for making requests from client side to server side returned zero value for status code. There are a lot of reasons why it might be except connection problems. Please refer to [StackOverflow](https://stackoverflow.com/a/26451773) for more detailed information.

**Comment by sergey-akhalkov** [comment] 2018-01-08 11:26
Hi @zjx, closing this, please feel free to reopen

**Closed by sergey-akhalkov** 2018-01-08 11:26 UTC
Labels: waiting-for-clarification
