### ISSUE TITLE
"Checking for update" delayed or Error 403

### ISSUE THREAD

**Issue by hrhosni** [microsoft/cordova-plugin-code-push#525] opened 2019-04-25 13:52 UTC
### Description

Everything was working great with Codepush until yesterday when we started suffering from an intermittent issue that happens when Codepush checks for an update. Our app is built to check for an update as soon as it loads. Here are the 3 scenarios we are experiencing when we open the app:

1) Codepush checks for update and the app opens normally

2) Codepush checks for update then instantly fails with the below error:

04-25 16:35:06.556 20606 20606 I chromium: [INFO:CONSOLE(36)] "[CodePush] Checking for update.", source: file:///data/user/0/com.digxxxxxxns.cxxxxs/files/codepush/deploy/versions/e564cffbebbdfd6d26377fcc857909791df48763588b22820a9995c88174bfac/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (36)
04-25 16:35:07.801 20606 20606 I chromium: [INFO:CONSOLE(41)] "[CodePush]  403: . StackTrace: Error: 403: 
04-25 16:35:07.801 20606 20606 I chromium:     at file:///data/user/0/com.digxxxxxxns.cxxxxs/files/codepush/deploy/versions/e564cffbebbdfd6d26377fcc857909791df48763588b22820a9995c88174bfac/www/plugins/code-push/script/acquisition-sdk.js:50:26
04-25 16:35:07.801 20606 20606 I chromium:     at XMLHttpRequest.xhr.onreadystatechange (file:///data/user/0/com.digxxxxxxns.cxxxxs/files/codepush/deploy/versions/e564cffbebbdfd6d26377fcc857909791df48763588b22820a9995c88174bfac/www/plugins/cordova-plugin-code-push/bin/www/httpRequester.js:30:36)", source: file:///data/user/0/com.digxxxxxxns.cxxxxs/files/codepush/deploy/versions/e564cffbebbdfd6d26377fcc857909791df48763588b22820a9995c88174bfac/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (41)

3) Codepush checks for update then gets stuck for about 10-15 seconds after which it either starts the download (if there is an update), or continues execution normally if there isn't.

Note that the above scenarios can all happen regardless of whether or not there actually is an update to be made. And they all happen with more or less the same probability. They happen on both Android and iOS.

### Additional Information

* cordova-plugin-code-push version: 1.11.18
* List of installed plugins: 
      "cordova-plugin-whitelist": {},
      "com.amitsinha.backashome": {},
      "cordova-plugin-dialogs": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-vibration": {},
      "cordova-plugin-device": {},
      "cordova-plugin-datepicker": {},
      "cordova-plugin-file": {},
      "cordova-plugin-media": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-zip": {},
      "cordova-plugin-appcenter-analytics": {},
      "cordova-plugin-appcenter-crashes": {},
      "cordova-plugin-spinner-dialog": {},
      "cordova-plugin-geolocation": {},
      "cordova-plugin-google-analytics": {},
      "cordova-plugin-local-notification": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-request-location-accuracy": {},
      "onesignal-cordova-plugin": {},
      "cordova-plugin-buildinfo": {},
      "cordova-plugin-googlemaps": {},
      "cordova-plugin-locationservices": {},
      "cordova-plugin-code-push": {}
* Cordova version: 8.0.0
* iOS/Android/Windows version: 
        android 7.0.0
        browser 5.0.4
        ios 4.5.5
* Does this reproduce on a debug build or release build? 
        both
* Does this reproduce on a simulator, or only on a physical device? 
       did not try on simulator

**Comment by alexandergoncharov** [comment] 2019-04-26 15:17
Hi @hrhosni  
Thank you for detailed reporting!

I reproduced your issue. As you said, 403 error show up on device in some cases after checking for updates. I will investigate this problem and keep you posted.

**Comment by hrhosni** [comment] 2019-04-26 21:43
Thank you @alexandergoncharov .
I would like to point out that the 403 is not the only problem. Scenario 3 mentioned above is another problem as well. Just mentioning this in case they are not related.

**Comment by hrhosni** [comment] 2019-05-02 13:34
Any updates @alexandergoncharov ? Thank you

**Comment by alexandergoncharov** [comment] 2019-05-14 11:23
Hi @hrhosni 
Sorry for delay!
Unfortunately I can't reproduce this issue now. After checking for updates everything is just fine. Do you still observe this behavior? I just would like to ensure that everything is fine for now.

**Comment by hrhosni** [comment] 2019-05-14 11:25
Hello @alexandergoncharov. We haven't seen this issue as of late.
Thank you.

**Comment by alexandergoncharov** [comment] 2019-05-14 11:32
Glad to hear that.
I'm going to close this issue as it was resolved. Feel free to reopen it if you faced this issue again.

**Closed by alexandergoncharov** 2019-05-14 11:32 UTC
Labels: bug, investigating

**Comment by mieszko4** [comment] 2019-07-24 16:46
It looks to me that is related to server issues - see https://github.com/microsoft/react-native-code-push/issues/1641

**Comment by hrhosni** [comment] 2019-07-25 14:07
Yes the issue kept recurring. 
We cannot make our app progress beyond the "loading screen" before establishing whether or not the Codepush update is mandatory. Which means that when a 403 error occurs, our app gets stuck on the loading screen indefinitely.
So we completely dropped Codepush to be honest.
