### ISSUE TITLE
Plugin 'File' not found, or is not a CDVPlugin... again

### ISSUE THREAD

**Issue by arnoldsi** [Microsoft/cordova-plugin-code-push#425] opened 2018-07-17 13:58 UTC
### Description

I managed to build the app and started in IOS and got the error
![image](https://user-images.githubusercontent.com/18511197/42821816-163a734a-89e2-11e8-9fe7-3c08ee256037.png)

### Reproduction

- cordova platform add ios
- cordova build ios

Run the simulator or device

### Additional Information

* cordova-plugin-code-push - 1.11.11
* List of installed plugins:
![image](https://user-images.githubusercontent.com/18511197/42821965-78d8e6d0-89e2-11e8-89aa-a588e370a408.png)
![image](https://user-images.githubusercontent.com/18511197/42821980-7e16eef8-89e2-11e8-9d13-dbe9df80143b.png)

* Cordova version: 6.5.0
* iOS cordova: 4.5.4
* iOs Device version: 11
* It reproduces in debug and release
* It reproduces in simulator and device

**Comment by arnoldsi** [comment] 2018-07-22 09:53
We have an automated Jenkins process that adding the platform, cordova installing the plugin after platform add (we also see the logs). The only way to make it work is to force (--force) remove the file plugin and install it again

**Comment by 1104931825** [comment] 2018-07-24 03:29
I have the same problem,The server showed that the update was successful but the app on the phone would not be updated

**Comment by alexandergoncharov** [comment] 2018-07-27 03:31
@arnoldsi , Is it possible to provide test project? I would like to debug it and find the reason. 
Anyway we have `after_plugin_add` hook for adding this plugin. 
Also, could you please clarify what exactly Jenkins do for the your project?

**Comment by arnoldsi** [comment] 2018-07-29 11:15
This is what jenkins does:
cordova platform add ios
cordova build ios

The only way for me to fix the issue was to run 
cordova plugin rm cordova-plugin-file --force
cordova plugin add cordova-plugin-file

after cordova platform add ios

**Comment by alexandergoncharov** [comment] 2018-08-09 16:34
@arnoldsi , Sorry for this delay.

Could you please remove `cordova-plugin-file`, `cordova-plugin-file-transfer` and `cordova-plugin-zip` from your config.xml just for testing and try again?

I think that you shouldn't add specially this plugins in your config file as this plugins will be added by hook of `cordova-plugin-code-push` plugin.

Please let me know about results of this testing.

Thanks,
Alexander

**Comment by arnoldsi** [comment] 2018-08-12 08:13
Hi @alexandergoncharov ,
Removing those plugins is not helping, I'm still getting the same issue. The only version that works smoothly for me is 1.9.4-beta

**Comment by alexandergoncharov** [comment] 2018-08-13 09:05
@arnoldsi ,
Could you please provide dummy project with detailed reprosteps? as I can't reproduce it. All works correct for me.

**Comment by corradio** [comment] 2018-08-17 09:41
I have the same issue that is solved by using the latest version of cordova-plugin-file (6.0.1).
However, due to https://github.com/Microsoft/cordova-plugin-code-push/issues/434, the old version of the plugin (4.3.3) is forced at each reinstall, and thus causes this issue.

**Comment by alexandergoncharov** [comment] 2018-08-21 15:55
Hi @corradio,

Could you please clarify do you mean that adding `cordova-plugin-file` (4.3.3) after every installing CodePush can call this error? I'm not sure about that because we use `add` which check if this plugin already installed and will not install in case if app already has it. Please correct me if I miss something.

Or could you please provide repro steps for reproducing this Error?

**Comment by corradio** [comment] 2018-08-22 06:25
Hi @alexandergoncharov,
You are right that in the case where the plugin is already installed, the issue doesn't appear.

Our issue is that we run `cordova prepare` in our CI (where the plugins are not already installed), which causes the installation of all plugins.
This means that even though the 6.0.1 version of `cordova-plugin-file` is specified, code-push will install the 4.3.3 version (due to the install script). I believe this is probably because of the order in which the plugins are installed.
The solution we had is to add another command that removes and re-installs the proper version of the `cordova-plugin-file` plugin after `cordova prepare` has been run, but it's not very clean.

Ideally the install script shouldn't force the install of any specific version. That should be specified in the dependencies instead.

**Comment by sambegin** [comment] 2018-08-22 19:59
Also happens on 
Cordova : 8.0.0
Cordova-ios : 4.5.5 
Code push : 1.11.12 

On a fresh installed project. Even if all the files plugin folders (cordova-plugin-file-transfer, cordova-plugin-file and cordova-plugin-zip) are present in the plugins folder, the definition of any of them is not inside the ios build.

Forcing a `cordova plugin remove <file plugin> --force` and reinstalling them fix the problem (but this is really inconvenient. 

I also see that the plugins definition are not present in the `fetch.json` file when they are installed from the codePush "afterPluginAdd" hook while they are defined in this file when we are manually installing them from the cordova command. Maybe this is related ?

**Comment by sambegin** [comment] 2018-08-22 20:13
2nd question (/thought) : 

Shouldn't you use the "before_compile" or "before_prepare" hook to install those missing dependencies (if they are missing) ? This would probably less interfere with projects that already installed those file plugin ? 

https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/

**Comment by sambegin** [comment] 2018-08-22 20:32
Just tested this : 

- Removed all plugins folder but keep `android.json`, `ios.json` and `fetch.json` file 
- Run `cordova prepare ios && cordova prepare android && cordova build`  

And I don't get the CDV file missing. However, like @corradio said, the cordova-plugin-file versions gets override by the code push hook script.

**Comment by alexandergoncharov** [comment] 2018-08-27 09:06
Hi @sambegin and @corradio ,
Sorry for delay.

@sambegin Thanks for suggestions about `before_compile/prepare/build` but in this case this script will work before every this action that really often and unnecessary. I think that one more checking if this plugin exist in `config.xml` should fix similar issues. I'll investigate it.

@corradio, Yeah, ideally this dependencies shouldn't be defined in script but we have to make it so because `cordova-plugin-file` (higher than 4.3.3) doesn't  support old cordova-android version less then 6.3.0. We would like to support new and old android version. We put this logic for installing this plugins with specific version in hooks because we would like to keep possibility to change plugin version for users if they would like to do so.

Also, I still can't reproduce `Plugin 'File' not found, or is not a CDVPlugin` issue.
Could please someone provide reprosteps for this issue?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment] 2018-08-29 17:25
HI @sambegin, @corradio, @arnoldsi ,

@yuri-kulikov implemented fix for preventing installation plugins if this is defined in config.xml.
I think it also should fix `Plugin 'File' not found, or is not a CDVPlugin` issue. Could please someone test it? Just download master and use it for plugin (cordova plugin add "path/to/root/dir/of/code-push-plugin").

Please let me know your results or if you have any questions.
Release will be soon.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment] 2018-09-12 11:13
Hi all,

Changes already published. 
I'm going to close this issue for now but please feel free to reopen it if you still have this issue.

**Closed by alexandergoncharov** 2018-09-12 11:13 UTC
Labels: bug, iOS, waiting-for-clarification
