### ISSUE TITLE
appVersion not honoured

### ISSUE THREAD

**Issue by sud80** [Microsoft/cordova-plugin-code-push#43] opened 2015-11-17 06:32 UTC
As per, https://github.com/Microsoft/code-push/tree/master/cli,
the appStoreVersion parameter indicates the minimum version of the app to which this push is applicable. 

I see that from the code, the plugin makes a http request as follows:
https://codepush.azurewebsites.net/updateCheck?deploymentKey=key&appVersion=appversion&packageHash=&isCompanion=false

Ideally it should not update if the appVersion on the hot code push package is greater then the current version being passed in the url. But it seems to still get the update
For example in our case the hot code push package had appVersion set to 0.45.2 and the url being invoked is 
https://codepush.azurewebsites.net/updateCheck?deploymentKey=masked-key&appVersion=0.45.0&packageHash=&isCompanion=false

It still get the package and prompts user to update.

**Comment by lostintangent** [comment] 2015-11-17 06:53
Which version of the Cordova plugin are you using from NPM? We fixed this bug a little while ago, so if you're using the latest version (1.1.0-beta) you shouldn't see this behavior. If you still see this using the latest, then that's definitely a bug.

**Comment by sud80** [comment] 2015-11-17 07:01
We are using "version": "1.1.0-beta". 
May be this seems like a server side issue?

**Comment by sud80** [comment] 2015-11-17 07:20
Also have a related question. If we do hot code push with appVersion 0.45.0 and another hot code push with appVersion 0.46.0, is it expected that the based on the client app version, it will download the appropriate push? or this use case is not supported?

**Comment by lostintangent** [comment] 2015-11-17 07:27
It could be a server issue, but after you filed this I tried it with the React Natice plugin and it worked, so I'm not completely sure. We can do further diagnosis tomorrow since this scenario should definitely work. Sorry for the inconvenience!

Regarding your second question, if you wanted to maintain two different App Store versions and update them independently via CodePush, we would recommend creating seperate deployments (or apps) to manage each one. When you release an update to a deployment it completely replaces the previous one, so you couldn't use a single app deployment to update both 0.45.0 and 0.46.0 at the same time. I'll note that we should add docs for how to manage this.

**Comment by sud80** [comment] 2015-11-17 07:37
Thanks for the quick update.

**Comment by sud80** [comment] 2015-11-17 15:22
Related to 2nd question: Does it make sense to expose a hook to override/specify the deployment key so the application can manage which deployment key to use instead of reading it from config.xml? This might make it more flexible.

**Comment by dlebu** [comment] 2015-11-17 19:22
@sud80 Thanks for filing this issue. We reproduced it and we are working on a server-side fix.

**Comment by dlebu** [comment] 2015-11-17 19:29
We also need to document better what `appStoreVersion` stands for. When we started the project, we used it as the minimum version for which the update is applicable, but we changed the behavior a while ago to be the exact version. After the fix, the server will return an update is the local and code push versions match, and no update if they are different.

**Comment by dlebu** [comment] 2015-11-17 20:10
@sud80 Regarding your second question, and keeping in mind the fixed version policy I mentioned in my previous comment, do you still see the need to handle multiple deployments in one app store version?

**Comment by silhouettes** [comment] 2015-11-18 02:29
Closing this issue as the fix has gone in on the server. Feel free to continue the discussion though!

**Closed by silhouettes** 2015-11-18 02:29 UTC

**Comment by sud80** [comment] 2015-11-18 05:05
@dlebu Thanks for the quick fix. Yes making it exact version of minimum version makes sense. We were making changes at our end to handle this as it was prompting even higher version of app to install the update. This helps. 

On the second question:
I am thinking having a hook to override deployment key might still be helpful. For example it can be used to support cases like if we want to push the hot code to controlled set of users (test flight / test installations) before mass pushing it.

**Comment by dlebu** [comment] 2015-12-08 11:23
@sud80 We relased [1.3.0-beta](https://github.com/Microsoft/cordova-plugin-code-push/releases) on Friday. This allows for an optional deployment key parameter to `checkForUpdate`. We renamed `apply` to `install`, so please make sure you make that change in your code when you upgrade to the latest version of the plugin. Thanks again for using CodePush and please keep the feedback coming.

**Comment by sud80** [comment] 2015-12-24 12:40
@dlebu Thanks this works good.
