### ISSUE TITLE
codePush.sync();

### ISSUE THREAD

**Issue by 1104931825** [Microsoft/cordova-plugin-code-push#430] opened 2018-07-24 02:32 UTC
codePush.sync(); Where does this code add what header files need to be imported

**Comment by alexandergoncharov** [comment] 2018-07-25 11:41
Could you please fill issue template https://github.com/Microsoft/cordova-plugin-code-push/blob/master/.github/ISSUE_TEMPLATE.md and provide as much info as you can because it is really hard to understand your issue?

Thanks,
Alexander

**Comment by pengzhiqiang110** [comment] 2018-07-26 00:55
<img width="718" alt="2018-07-26 8 39 39" src="https://user-images.githubusercontent.com/37108809/43234807-e3a2ac1a-90b0-11e8-95ad-0eb04026be8c.png">
Is this code to check for updates written in the index.js file?

<img width="452" alt="2018-07-26 8 42 52" src="https://user-images.githubusercontent.com/37108809/43234849-106a16b6-90b1-11e8-84e9-46c7f9be27ff.png">
This is the configuration information in the XML file

<img width="550" alt="2018-07-26 8 43 46" src="https://user-images.githubusercontent.com/37108809/43234882-38597a68-90b1-11e8-8f6f-108882f3b9a2.png">
This is the information for installing the plug-in.

<img width="367" alt="2018-07-26 8 45 42" src="https://user-images.githubusercontent.com/37108809/43234898-4d6b69f2-90b1-11e8-8a57-75a537410161.png">
This is the version of cordova

codePush.sync(); This code in the official document said after the program started, I still do not understand where to put it  
Looking forward to your reply

**Comment by alexandergoncharov** [comment] 2018-07-27 03:39
Hi @1104931825, @pengzhiqiang110 

There can be some places to put CodePush.sync() method. it is depend of your logic. Just for example you can put it in `onDeviceReady`. In this case CodePush checks updates after every start of app.
You can check example projects for getting more details:  https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic
Also you can check advanced test project for more detailed setup codepush.

Please let me know if it was helpful for you or you have any questions.

Thanks,
Alexander

**Comment by pengzhiqiang110** [comment] 2018-07-27 08:32
@alexandergoncharov  I set the file according to what you said. Now, if I update it, it will report an error.The error is "An error occured while checking for updates ".
<img width="959" alt="1" src="https://user-images.githubusercontent.com/37108809/43310531-633ced96-91ba-11e8-82d5-6819685d4cad.png">
<img width="579" alt="2" src="https://user-images.githubusercontent.com/37108809/43310532-6377382a-91ba-11e8-93bf-d37beb5f4ad7.png">
Above are the console information for error reporting and the historical version I posted,What is the cause of the error or how can I check the cause of the error? Looking forward to your reply

**Comment by 1104931825** [comment] 2018-08-01 01:13
Did anyone answer the question? Do you speak Chinese?

**Comment by NickToropov** [comment] 2018-08-02 11:17
Hi @1104931825, could you provide us with demo app that reproduces your issue?

**Comment by 1104931825** [comment] 2018-08-06 00:53
[cordovaHotUpDate.zip](https://github.com/Microsoft/cordova-plugin-code-push/files/2260845/cordovaHotUpDate.zip)

This is my demo. Could you please help me see what the problem is? Looking forward to your reply

**Comment by 1104931825** [comment] 2018-08-06 01:06
@NickToropov  @alexandergoncharov  [cordovaHotUpDate.zip](https://github.com/Microsoft/cordova-plugin-code-push/files/2260876/cordovaHotUpDate.zip)
This is my demo. Could you please help me see what the problem is? Looking forward to your reply

**Comment by alexandergoncharov** [comment] 2018-08-06 14:01
@pengzhiqiang110 , I see that it is just https request issue.  Could you please clarify have you set  `access-origin` and `content-security-policy`?
It is 2 and 3 steps from https://github.com/Microsoft/cordova-plugin-code-push#supported-cordova-platforms

**Comment by alexandergoncharov** [comment] 2018-08-06 14:31
@1104931825 Thanks for test project. I found that you used `Content-Security-Policy` in your `config.xml` file but is should be used in your html file.
I removed this Content-Security-Policy line form config.xml and added it in index.html file with replacing existing `Content-Security-Policy` and successfully got update.

Please let me know if it fixed you issue or you have any questions.

**Comment by 1104931825** [comment] 2018-08-06 15:38
@alexandergoncharov   thank you very much.  My problem has been solved ,Can I follow your twitter

**Comment by alexandergoncharov** [comment] 2018-08-07 07:19
@1104931825 Good news :)

Unfortunately I don't use twitter. But you can use CodePush twitter https://twitter.com/mscodepush and AppCenter twitter https://twitter.com/vsappcenter

So, as issue was resolved I'm going to close this issue. Please feel free to reopen this issue if you have any questions.

Thanks,
Alexander

**Closed by alexandergoncharov** 2018-08-07 07:19 UTC
Labels: question, waiting-for-clarification
