### ISSUE TITLE
Ionic 4 cordova is not available when updating via Code Push for Android app

### ISSUE THREAD

**Issue by alexp25** [microsoft/cordova-plugin-code-push#596] opened 2020-01-16 13:54 UTC
### Description

I am using Code Push cordova plugin for updating an Ionic 4 Cordova Android app. It used to work with Ionic 3 but since Ionic 4, Code Push is broken. The update seems to work but then Cordova is no longer available and therefore all native plugins are no longer working.

### Reproduction
This is the command I am using to release an update:

appcenter codepush release-cordova -a <app_name> -d Staging --description "new update"

### Additional Information

I am using the latest version of the cordova-plugin-code-push (1.12.0), ionic 4, angular 8, cordova-android 8.0.0.

* cordova-plugin-code-push version: 1.12.0
* Ionic version: 5.2.6
* Cordova version: 8.1.2
* Cordova-android version: 8.0.0
* iOS/Android/Windows version: Windows 10, Android 8.0.0
* debug (Staging) release
* Issue applies to physical device only

* List of installed plugins:
cc.fovea.cordova.purchase 8.1.1 "Purchase"
code-push 3.0.1 "CodePushAcquisition"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-mode 0.7.3 "BackgroundMode"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-brightness 0.1.5 "Brightness"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-cocoapod-supportx 1.7.3 "Cordova CocoaPods Dependency Support"
cordova-plugin-code-push 1.12.0 "CodePush"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-device-motion 2.0.1 "Device Motion"
cordova-plugin-device-orientation 2.0.1 "Device Orientation"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 8.1.1 "Google SignIn"
cordova-plugin-gyroscope 0.1.4 "Device Gyroscope"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-iosrtc 5.0.0 "iosrtc"
cordova-plugin-is-debug 1.0.0 "IsDebug"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-mauron85-background-geolocation 3.0.1 "CDVBackgroundGeolocation"
cordova-plugin-media 5.0.3 "Media"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.0 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
cordova.plugins.diagnostic 5.0.0 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.6.0 "OneSignal Push Notifications"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"

**Comment by Krasavinigor** [comment] 2020-08-28 14:05
Hi @alexp25! 
Thank you for reporting! 
Unfortunately, I couldn't reproduce this issue. Could you please provide a demo project with this issue?

**Comment by alexp25** [comment] 2020-08-28 14:35
I have since solved the issue. I was using ```ionic build --prod --release``` to create the build before code push (which was working with ionic 3). Now it works after I make the full build ```ionic cordova build android --prod --release```.

**Comment by Krasavinigor** [comment] 2020-08-31 06:43
Great! Thank @alexp25! 
I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Closed by Krasavinigor** 2020-08-31 06:43 UTC
Labels: waiting-for-clarification
