### ISSUE TITLE
Changes disappear after app restart

### ISSUE THREAD

**Issue by krzyhub** [Microsoft/cordova-plugin-code-push#451] opened 2018-09-24 10:16 UTC
Hello,

After new version of app is pushed I can see that app was updated on my device after I launched it (installMode: InstallMode.IMMEDIATE). In the console I can see that everything related to installation process is fine:
```
CODE PUSH SUCCESSFUL: 5
[CodePush] Checking for update.
[CodePush] Awaiting user action.
CODE PUSH SUCCESSFUL: 6
```
Then I confirm to continue installation.
```
CODE PUSH SUCCESSFUL: 7
[CodePush] Downloading update
[CodePush] Package download success
CODE PUSH SUCCESSFUL: 8
[CodePush] Installing update
[CodePush] Applying diff update
[CodePush] Verifying hash for folder path: /codepush/deploy/versions/d183f3ed36bd4c877009c18ae9a51d2e19cb0f0a9a8902606c14a419bb314f16/
[CodePush] The update contents succeeded the data integrity check.
```
But after closing and starting app again it shows me old content, but saying that **App is up to date**. In console I can see that `this.codePush.getCurrentPackage()` really shows the last and proper update description.

My update code is very simple:
```
    platform.ready().then(() => {
        ...
      this.checkCodePush();
    });
```

```
checkCodePush() {
      this.codePush.sync({
       updateDialog: {
        appendReleaseDescription: true,
        descriptionPrefix: "\n\nChange log:\n"

       },
       installMode: InstallMode.IMMEDIATE
    }).subscribe(
      (data) => {
       console.log('CODE PUSH SUCCESSFUL: ' + data);
      },
      (err) => {
       console.log('CODE PUSH ERROR: ' + err);
      }
    );
 }

```
For more, I can say that when I plug in my phone to Chrome Dev Tools and update app for the first time, then it is okay till I refresh the page. After refresh there is an information that page couldn't be loaded because of missing file:///data/user/0/io.ionic.starter/files/codepush/deploy/versions/d183f3ed36bd4c877009c18ae9a51d2e19cb0f0a9a8902606c14a419bb314f16/www/index.html

Also, there isn't any informations about rollback.

I will appreciate any help.

**Comment by alexandergoncharov** [comment] 2018-09-26 15:16
Hi @krzyhub ,
Thanks for reporting!

Could you please clarify is it Android or Ios issue? or both?
And could you please provide dummy project?

Thanks,
Alexander

**Comment by khlewesamer** [comment] 2018-09-27 10:37
I have the same issue 
Platform android , I didn't try in ios yet

**Comment by krzyhub** [comment] 2018-09-27 10:42
Hi @alexandergoncharov ,
For sure it is Android issue (tested on two different devices).
Here is a dummy project example: https://github.com/krzyhub/cpionic

**Comment by davec21** [comment] 2018-09-28 16:49
I am having same issue with latest codepush. 

iOS appears to work.  That said, there is an issue with iOS and the latest ionic webkit webview. The issue is with the way the webview plugin handles content loading. There is a line in the .m file that needs to be tweaked.

Not sure if that's what is going on with android too, but with iOS it would just 404. Android will load it, but it doesn't seem to retain it after close.

**Comment by davec21** [comment] 2018-09-28 18:10
Just a quick follow up, I tried looking into it. I can't figure out what's going on.. It's almost like the call to load the deployment url is being ignored. Paths are the same, everything is fine.. it just seems to want to load the index from the android_assets folder regardless.

**Comment by davec21** [comment] 2018-09-28 19:10
Did some even more digging.  Looks like it's a race-condition with the ionic webview implementation. 

Basically what happens is that it tries to load the local file:///android_assets index.html.  The ionic webview captures that, stops the load, then tells it to load the https://localhost:8080 version of it. So while it's stopping the loading and trying to navigate to the new url, it is preventing the code-pushed page from loading.

**Comment by krzyhub** [comment] 2018-09-29 07:38
I can confirm that without webview plugin update works, so, as davec21 said it would be a conflict between webview plugin and code-push plugin.

**Comment by krzyhub** [comment] 2018-10-01 14:44
Works for me :+1:

**Comment by atftech-artyom** [comment] 2018-10-09 10:57
This pull request solves issue with Android: #454

**Comment by vickydadhich** [comment] 2018-10-16 16:37
It worked for me too.. thanks a lot @alexandergoncharov you saved my day

**Comment by lperezb** [comment] 2018-10-19 18:42
@alexandergoncharov awesome! This works... wasted almost two days to this.... hope it gets fix

**Comment by alexandergoncharov** [comment] 2018-11-14 11:37
Hi all, @krzyhub, @khlewesamer, @davec21, @vickydadhich,  @perezb,
Could please some one helps to test this PR: https://github.com/Microsoft/cordova-plugin-code-push/pull/454 and please let me know if you found any issues.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment] 2018-11-15 16:15
Hi all,

Changes already in master and in new Cordova release. So, I'm going to close this issue for now but please feel free to reopen it if you have any issues.

Thanks,
Alexander

**Closed by alexandergoncharov** 2018-11-15 16:15 UTC
Labels: android, fix-in-pull-requests, investigating

**Comment by 349989153** [comment] 2019-01-02 09:32
Ran in to the same issue. I didn't use `cordova-plugin-ionic-webview` but `cordova-plugin-crosswalk-webview`.

And it happened only on Android devices, not iOS.

All the related package versions are: 
- cordova-android: 6.4.0
- cordova-plugin-crosswalk-webview: 2.4.0
- cordova-plugin-code-push: 1.11.11

Any advice, please?

**Comment by 349989153** [comment] 2019-01-02 12:19
I update `cordova-plugin-code-push` to `1.11.16` but no working.

**Comment by 349989153** [comment] 2019-01-03 07:48
I rm the `cordova-plugin-crosswalk-webview` and add `platform android` again, but the issue is still there.Start to question if I miss any key steps of using codePush

**Comment by metinjakupi** [comment] 2021-01-12 15:15
Bump!
