### ISSUE TITLE
iOS 10.2: Old code inside www/ after appstore update

### ISSUE THREAD

**Issue by golovan** [Microsoft/cordova-plugin-code-push#207] opened 2017-01-11 13:35 UTC
After update from appstore, application still uses old codepush update which was downloaded earlier on device for previous version of application. It's the problem because our application will not work with BE until it (app) has the latest version. If we release codepush update for this new appstore version that helps but looks weird. As just after appstore update user sees application downloading update then codepush update process starts and user has to reload an app to make it work. We were able to repeat this issue on the latest iOS 10.2 (on all devices with this version). This's ionic1 cordova application. Is it possible to force new appstore release to use its own code and ignore previous codepush update? Do you have any thoughts when this might be managed/fixed?

**Comment by sergey-akhalkov** [comment] 2017-01-11 15:13
@egolovan - hi!
Agreed, releasing codepush update is weird solution, but for current version of `cordova-plugin-code-push` it is the only possible solution. There are two PRs should fix the issue, #201 and #202 are waiting to be merged and released. Hoping this will happen soon.

**Comment by egolovan** [comment] 2017-01-11 15:20
Thank you for your answer, @sergey-akhalkov! We tried #202 yesterday w/o any success. On iOS 10.2 that didn't work. ;( Hope there will be some solution soon!

**Comment by TombolaShepless** [comment] 2017-01-11 15:55
@sergey-akhalkov do you know when those PRs will be merged? I have put a comment on #201 expressing my concern regarding the activity of the CodePush project and its long term future. I don't mean to sound disrespectful/ungrateful - I just want to make a sounds decision for the business I work for.

**Comment by sergey-akhalkov** [comment] 2017-01-12 12:11
@TombolaShepless - hi!
Sorry for the silence on our side. Please see https://github.com/Microsoft/code-push/issues/366 answer relates to development state of CodePush solution. Unfortunately, for now I haven't any information about release plans, but will let you know if there is any news.

**Comment by sergey-akhalkov** [comment] 2017-01-13 14:35
@egolovan - hi!
I've tried to reproduce the issue with no luck with following repro steps:
1. Build and run app with version `1.0.0` having `"initial value"` string in `index.html` file.
2. Release and install an update - change `"initial value"` string to `old value` in `"index.html"` file.
3. Build and run app with version `1.0.1` having `"new value"` string in `index.html` file.

At the end I've got `index.html` with `"new value"` string. So could you please provide me with more info? (maybe `code-push-cli` version, `cordova-plugin-code-push` version - execute `code-push -v` and `cordova plugins ls` commands)

**Comment by egolovan** [comment] 2017-01-13 14:47
@sergey-akhalkov, thank you for researching this! Did you try it on iOS 10.2? 

code-push -v: 1.12.3-beta

code-push 1.9.0-beta "CodePushAcquisition"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-fabric-plugin 1.1.1 "cordova-fabric-plugin"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-badge 0.7.2 "Badges"
cordova-plugin-camera 2.3.1-dev "Camera"
cordova-plugin-code-push 1.9.2-beta "CodePush"
cordova-plugin-device 1.1.3-dev "Device"
cordova-plugin-dialogs 1.2.2-dev "Notification"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.5.2-dev "File Transfer"
cordova-plugin-geolocation 2.2.1-dev "Geolocation"
cordova-plugin-inappbrowser 1.4.1-dev "InAppBrowser"
cordova-plugin-nativeaudio 3.0.7 "Cordova Native Audio"
cordova-plugin-network-information 1.2.2-dev "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.4-dev "StatusBar"
cordova-plugin-themeablebrowser 0.2.17 "ThemeableBrowser"
cordova-plugin-uniquedeviceid 1.3.1 "UniqueDeviceID"
cordova-plugin-vibration 2.1.2 "Vibration"
cordova-plugin-whitelist 1.2.3-dev "Whitelist"
cordova-plugin-x-socialsharing 5.1.3 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
es.keensoft.fullscreenimage 1.0.1 "Full Screen Image"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
nl.x-services.plugins.touchid 3.2.0 "Touch ID"
onesignal-cordova-plugin-pgb-compat 1.13.1 "OneSignal Push Notifications PGB Compat"
uk.co.cv-library.plugins.DropboxChooser 2.0.0 "Dropbox Chooser"

**Comment by sergey-akhalkov** [comment] 2017-01-24 09:12
@egolovan - hi, I've tried to reproduce the issue several times using iOS 10.2 and other options, but with no luck.
>We tried #202 yesterday w/o any success.

Could you please try both #201 and #202 due to first one could be also related to the issue (as for https://github.com/Microsoft/cordova-plugin-code-push/issues/196) and let me know if the issue is still reproduces?

**Comment by scopsy** [comment] 2017-01-31 15:03
Experiencing the exact same thing. This is blocking me from using Code-push in my organization.

**Comment by sergey-akhalkov** [comment] 2017-01-31 15:10
@scopsy, could you please try to apply #201 and #202 and let me know if it helps?

**Comment by xiehaom7** [comment] 2017-01-31 16:08
Hi @sergey-akhalkov, I have the same problem. 

When my app gets an update from Code-Push, it will change to load codes from that package folder. Then, updating the app (through like testflight) will only update the codes in the original place while the app will still load codes from the package folder. So, the app looks like not updated.

Also, currently, the Code-Push only check the app version based on the metadata in the package folder as long as it exists. So, it isn't aware other app updates.

I've tested #202 and it can let code-push know the real binary version but I still have to push an update to the Code-Push Server.

**Comment by sergey-akhalkov** [comment] 2017-02-01 12:43
@xiehaom7 - have you tested #202 in pair with #201? It is important to apply changes from #201 due to it fixes similar issue - #196. I've also got confirmation that those PRs would resolve https://github.com/Microsoft/cordova-plugin-code-push/issues/199#issuecomment-274250778

Also [the issue may caused by `.DS_Store` files](https://github.com/Microsoft/cordova-plugin-code-push/issues/199#issuecomment-272420307) and `__MACOSX` folder. 
I will probably implement logic which will skip those items like `react-native-code-push` does https://github.com/Microsoft/react-native-code-push/commit/66a301474a01c11732db9b7c7ee57fc0dffd0931

**Comment by tatatananana** [comment] 2017-02-01 14:09
In iOS 10.2 this line (https://github.com/Microsoft/cordova-plugin-code-push/blob/master/src/ios/Utilities.m#L18) always returns NSFileModificationDate = "1970-01-01 00:00:00 +0000" this is the source of the problem.

it causing the clearDeploymentsIfBinaryUpdated (https://github.com/Microsoft/cordova-plugin-code-push/blob/master/src/ios/CodePush.m#L243) to not function well

**Comment by sergey-akhalkov** [comment] 2017-02-01 15:01
@tatatananana, oh, I see, thank you, I've missed that #201 helps for android apps only, sorry! 
I'll probably try to find solution fixing the issue and prepare PR.

**Comment by tatatananana** [comment] 2017-02-02 08:07
@sergey-akhalkov I did a quick & dirty fix (https://github.com/tatatananana/cordova-plugin-code-push/blob/master/src/ios/Utilities.m#L6) that solves the problem by using the build version.
I've tested it & it seems to do the job, I did a research on the project regarding the usage of ApplicationTimestamp i don't see any other use if so, well just need to clean the code.

**Comment by max-mironov** [comment] 2017-02-02 13:33
Hi @tatatananana, thank you for your input. I've tried to verify the _getApplicationBuildTime_ function and it seems working correctly for me. Unfortunately I was verifying it on simulator with iOS 10.0 (not 10.2) because at that moment I don't have real device near at hand. Is it possible for you to check it on another iOS version to see if this issue is related to this?

**Comment by tatatananana** [comment] 2017-02-02 13:40
@max-mironov tested on real devices: ios 10.2 & ios 9.3.3

**Comment by max-mironov** [comment] 2017-02-03 14:07
Hi @tatatananana, I've added pull request that could possibly fix your issue, do you have a chance to verify if this is working for you?

**Comment by stevenraines** [comment] 2017-02-10 21:43
Having the same issue on android and iOS. Will look into PR. Any update on release plans?

**Closed** 2017-02-23 19:27 UTC
Labels: bug

**Comment by sergey-akhalkov** [comment] 2017-02-27 09:22
@stevenraines, we've recently released `cordova-plugin-code-push@1.9.3-beta`, so you could update to verify, please let us know if you see any issues.

**Comment by huilianyi** [comment] 2017-03-23 07:31
Is this bug fixed? at version 1.9.3?

**Comment by max-mironov** [comment] 2017-03-23 08:01
@huilianyi - yes, this bug should be fixed in latest version. Do you still see the issue?
