### ISSUE TITLE
Cordova www/index failed to load after update on iOS 9.3

### ISSUE THREAD

**Issue by pke** [Microsoft/cordova-plugin-code-push#171] opened 2016-10-07 02:06 UTC
My app is downloading a correct ZIP file with new content. It contains the `www` folder and inside it an `index.html`. The app is supposed to update on resume but it fails to load `www/index.html` from the newly installed package.

There is no way to remove/rollback this update since it was the first one deployed :(

```
[Log] [CodePush] An update is available. {"appVersion":"2.3.21","deploymentKey":"GshPqCbcfaqimBqHcfjUOmN20ByV41r96RnWe","description":"","downloadUrl":"https://codepush.blob.core.windows.net/storagev2/BsCx_IhjBR3fcmuzP-F47hW8yCKJ41r96RnWe","isMandatory":false,"label":"v1","packageHash":"abe686cfebe687aab862da367fa106c5c3ede12c11427d61ce14bf09e2e9b677","packageSize":1368786,"failedInstall":false} [CodePush] Downloading update (codePushUtil.js, line 37)
[CodePush] Package download success: {"deploymentKey":"GshPqCbcfaqimBqHcfjUOmN20ByV41r96RnWe","description":"","label":"v1","appVersion":"2.3.21","isMandatory":false,"packageHash":"abe686cfebe687aab862da367fa106c5c3ede12c11427d61ce14bf09e2e9b677","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/library-nosync/codepush/download/update.zip"}
[CodePush] Installing update (codePushUtil.js, line 37)
[CodePush] Install succeeded. (codePushUtil.js, line 37)
[CodePush] Update is installed and will be run when the app next resumes. (codePushUtil.js, line 37)
```

After resuming the app I am getting this and the splash screen remains visible:

```
[Error] Failed to load resource
file:///var/mobile/Containers/Data/Application/FBCBA4DB-668A-4F81-8D15-17F0ED689608/Library/NoCloud/codepush/deploy/versions/abe686cfebe687aab862da367fa106c5c3ede12c11427d61ce14bf09e2e9b677/www/index.html (index.html, line 0)
[Log] [CodePush] Checking for update. (codePushUtil.js, line 37)
[Log] [CodePush] Reported status: {"status":1,"label":"v1","appVersion":"2.3.21","deploymentKey":"GshPqCbcfaqimBqHcfjUOmN20ByV41r96RnWe","previousLabelOrAppVersion":"v1","previousDeploymentKey":"EarhW_VQyFDVvypil_P_cpjSevsN41r96RnWe"} (codePushUtil.js, line 37)
[Log] [CodePush] App is up to date. (codePushUtil.js, line 37)
```

I am using cordova plugin `1.8.0-beta`

**Comment by pke** [comment] 2016-10-14 10:48
maybe this is related to #156? What is your progress on that @silhouettes? Can't ask on the other issue cause its locked down.

**Comment by silhouettes** [comment] 2016-10-19 03:21
@pke - Apologies for the oversight, the fix for #156 has been published in `1.9.0-beta` ([release notes](https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.9.0-beta)). If you end up trying it, I'd love to know if that fixes this issue! I'll try to get around to investigating this otherwise.

**Comment by pke** [comment] 2016-10-20 14:00
@silhouettes I tested the new beta now. It's not completely solving the problem.

All goes fine when downloading the update on app resume.

```
[CodePush] Checking for update.
[CodePush] An update is available. {"appVersion":"4.0.0","deploymentKey":"XXXXXXXXXXXXXXXXXXXXXXX","description":"","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/xM65QnLWQNzTBJq4rDUch0cWsMZe41r96RnWe","isMandatory":false,"label":"v2","packageHash":"26c339e4aad311c280a18677d266ffe37417bacc2dee59282accccd3a24f3b97","packageSize":427416,"failedInstall":false}
[CodePush] Downloading update
[CodePush] Package download success: {"deploymentKey":"XXXXXXXXXXXXXXXXXXXXXXXX","description":"","label":"v2","appVersion":"4.0.0","isMandatory":false,"packageHash":"26c339e4aad311c280a18677d266ffe37417bacc2dee59282accccd3a24f3b97","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
[CodePush] Installing update
[CodePush] Install succeeded.
[CodePush] Update is installed and will be run when the app next resumes.
```

However when resuming the app again it stays very long (several seconds) in the splashscreen. No console output during this time. But then eventually displaying this error dialog and the app appearing in the background.
![screenshot_2016-10-20-15-46-41](https://cloud.githubusercontent.com/assets/164625/19562884/531f9ea0-96de-11e6-96bf-9e273a9809cb.png)


Then the app terminates itself. There was no `[CodePush] Checking for update.` ouput during that time.
When restarting everything worked though.
So the experience is still a little rough and worse than it has been in the previous versions.
Maybe you can investigate more what changed over time.

**Comment by silhouettes** [comment] 2016-10-20 17:52
Thanks @pke, I'll have a look.

**Comment by pke** [comment] 2016-11-10 09:28
@silhouettes Any news on that? Otherwise I'd remove the plugin from our app, since it also seems to slow down initial page refresh a lot when it looks for new versions.

**Comment by silhouettes** [comment] 2016-11-10 19:03
Hi @pke, I'm really sorry but we don't have the resources to investigate this at the moment. I'd really like to work on this, but we genuinely are unable to. I'll update this thread once we do though.

**Comment by vladimir-kotikov** [comment] 2016-12-23 15:37
@pke, hi

Are you still seeing this? This looks cryptic and we probably will need more detailed steps to reproduce the problem. Also having a minimal app where the problem reproduces would be awesome.

**Comment by pke** [comment] 2016-12-23 17:29
Yes saw that yesterday again and removed the code push plugin for now. There are to many issues still unsolved that it doesn't make much sense for us right now. See my other open issues. Also detecting when a code push update would be possible is currently not easy to detect in a CI environment.

**Comment by vladimir-kotikov** [comment] 2016-12-26 07:35
Yeah, I agree, it might be frustrating, yet I'd really appreciate if you could provide some additional details. Right now it sounds like the downloaded package was  somehow broken, so the page hasn't been found on device, but this is just a speculation and needs an additional confirmation.

**Comment by wssss** [comment] 2017-02-07 07:55
hope this issue can be fixed .

**Comment by max-mironov** [comment] 2017-03-03 14:19
Hi @pke, I've tried to repro this now with our [basic sample](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic) and latest cordova plugin but with no luck, so I'm closing the issue now because we don't have any additional clues on how to reproduce it. If you still experience that issue please create a separate ticket and provide us with more info regarding this as it is described [here](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/.github/ISSUE_TEMPLATE.md). Thank you!

**Closed by max-mironov** 2017-03-03 14:19 UTC
Labels: investigating
