### ISSUE TITLE
CodePush error if no deployment exists

### ISSUE THREAD

**Issue by bradzacher** [Microsoft/cordova-plugin-code-push#265] opened 2017-07-09 23:34 UTC
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

I have built a new app which hasn't been released yet. We've added code push, but as we haven't deployed to prd, we haven't pushed any code push releases to that slot yet.

In the app it checks for update, finds an update, and then errors out because the update doesn't have a download URL:
![screen shot 2017-07-10 at 9 22 45 am](https://user-images.githubusercontent.com/7462525/27998380-8d4f1924-6551-11e7-8146-6cd3a2cbc36a.png)

Here is the result of running the history for prd, as you can see it's empty:
<img width="759" alt="screen shot 2017-07-10 at 9 27 35 am" src="https://user-images.githubusercontent.com/7462525/27998466-fa2b4ddc-6552-11e7-9325-754734623de7.png">

This happens on both iOS and Android. It seems to be a bug with how the server handles no pushes.

I have a non-blocking toast message that appears when there is an update downloading (so that it's not so ambiguous to my support people if there's a new release), but it shows up on every single page load.

The problem is that I don't really want to release my app, and have a day 0 codepush download.

**Comment by sergey-akhalkov** [comment] 2017-07-10 12:11
Hi @bradzacher, thanks for reaching us. Could you please take a look at https://github.com/Microsoft/cordova-plugin-code-push/issues/256 and let me know if you have the same issue? If so, please take a look at https://github.com/Microsoft/cordova-plugin-code-push/issues/256#issuecomment-312884637 - you need to upgrade your `cordova-plugin-code-push` version to [1.9.5](https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.9.5-beta)

Please let me know if it helps.

**Comment by max-mironov** [comment] 2017-07-14 13:32
@bradzacher - just a friendly ping on this.

**Comment by max-mironov** [comment] 2017-07-17 07:21
Closing the issue for now, please reopen if the issue is still actual for you.

**Closed by max-mironov** 2017-07-17 07:21 UTC
Labels: bug, duplicate, fix-in-master, waiting-for-clarification
