### ISSUE TITLE
The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 1.)

### ISSUE THREAD

**Issue by Wallethub** [Microsoft/cordova-plugin-code-push#406] opened 2018-05-07 20:41 UTC
With the latest version of the plugin if we do: codePush.restartApplication()
we get: Failed to load resource: The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 1.)
This is only after updates are downloaded and installed. So you can think of it as being called right inside the success callback of the sync method. We have sync set with installMode: InstallMode.ON_NEXT_RESTART and we call codePush.restartApplication() after sync is done and we present some info to the user.
Happens in the latest ios under WKWebview engine.

**Comment by alexandergoncharov** [comment] 2018-05-10 16:05
Hi @Wallethub,

Thanks for reporting!
Could you please provide full code example of using codePush? It will be helpful for reproducing issue and finding approach for fixing this issue. 

Also, Could you please provide some additional info:

- cordova-plugin-code-push version
- List of installed plugins:
- Cordova version:
- iOS/Android/Windows version:
- Does this reproduce on a debug build or release build?
- Does this reproduce on a simulator, or only on a physical device?

**Comment by alexandergoncharov** [comment] 2018-05-17 13:09
Hi @Wallethub ,

I'll close this issue for now as I didn't hear from you in a while. Please feel free to reopen it if you will have questions or when you provide additional info.

Thanks,
Alexander

**Closed by alexandergoncharov** 2018-05-17 13:09 UTC

**Comment by chung-leong** [comment] 2018-05-20 02:06
I'm getting the same error when I tried to do a mandatory update. The update installs successfully, but then when the call is made to loadRequest to switch to the new location, WkWebView balks at the request, emitting a kCFErrorDomainCFNetwork error 1. 

After clearing the deployment and adding a non-mandatory update, it works properly again (updating on restart).

This happens on a iPhone 5C running iOS 10.3.3. The plugin version is 1.11.10.

**Comment by alexandergoncharov** [comment] 2018-05-21 04:43
Hi @chung-leong ,
Thanks for reporting!

Could you please provide example about your using codePush, logs with stacktrace or/and test project with reproducing issue with detailed repro-steps? It can really help me reproduce issue and find the reason of issue.

Thanks,
Alexander

**Comment by liangwenzhong** [comment] 2018-05-23 02:38
I had the same problem.
ioniv -v 3.7.0
cordova -v 6.5.0
cordova-plugin-wkwebview-engine 1.1.2
cordova-hot-code-push-plugin 1.5.2

**Comment by eskhool** [comment] 2018-07-01 18:11
The readme states

> iOS (cordova-ios 3.9.0+) - Note: In order to use CodePush along with the cordova-plugin-wkwebview-engine plugin, you need to install v1.5.1-beta+ version of cordova-plugin-code-push, which includes full support for apps using either WebView.


Is this still true at 1.11.11 or just that the documentation is lagging behind?

In any case, I can also verify that this issue persists with the following versions:

Running on device iPhone 5s
iOS 10.3.3
cordova - 8.0.0
<engine name="ios" spec="^4.5.4" />
<plugin name="cordova-plugin-wkwebview-engine" spec="^1.1.4" />
<plugin name="cordova-plugin-code-push" spec="^1.11.11" />

**Comment by northkode** [comment] 2018-08-08 17:59
This issue is still there for iOS 11.3 and the latest code push ^1.11.11
