### ISSUE TITLE
code-push works on IOS9, IOS10, but fails on IOS8

### ISSUE THREAD

**Issue by MrWillow** [Microsoft/cordova-plugin-code-push#179] opened 2016-10-20 12:13 UTC
First: Thank you for a great product that takes the headache out of minor bigfixes.

We have implemented it in our Cordova project.
Everything works as advertised on both Andoid and IOS, with the exception of IOS8.

We have tested code-push by making minor changes in version (like going from 1.0.6 to 1.0.7), which we display in our app.
Here is a code snippet:

```
this.onDeviceReady = function() {
  if( typeof codePush !== 'undefined' ){
    alert("calling sync() hoping for 1.0.7 soon.");
    codePush.sync();
  }
```

On IOS8 on an old IPhone 4S, we see the alert when app starts, but it never updates. 
All works fine in IOS9 and IOS10.
What could be causing this?
If you need more information, please ask.

We use v1.8.2-beta plugin.

**Comment by silhouettes** [comment] 2016-10-20 17:49
Hi @MrWillow - that's very unusual. If you don't mind, could you add some debugging code to see how far it's getting in the sync using the `syncStatus` callback, like in this example? https://github.com/Microsoft/cordova-plugin-code-push/blob/master/samples/basic/www/js/index.js#L40

**Comment by Gerarddus** [comment] 2016-10-26 08:36
Hi @silhouettes, Im working on the same project as @MrWillow. I copied the example code in our existing cordova project and built (XCode 8) the ios-app on a iOS8 device (iPhone 4s)
This is the output:

Output in xcode: 

> 
> 2016-10-25 09:01:53.821 Appnameremoved[28905:2938494] [CodePush] Checking for update.
> 2016-10-25 09:01:56.902 Appnameremoved[28905:2938494] [CodePush] An update is available. {"appVersion":"1.0.7","deploymentKey”:"removed","description":"Test push naar 1.0.61","downloadUrl":"https://codepush.blob.core.windows.net/removed","isMandatory":true,"label":"v4","packageHash”:"removed","packageSize":73222318,"failedInstall":false}
> 2016-10-25 09:01:56.903 Appnameremoved[28905:2938494] [CodePush] Awaiting user action.
> 2016-10-25 09:01:56.904 Appnameremoved[28905:2938494] Alerting user.

The app notifies that there is an update available that has to be installed.


> 2016-10-25 09:02:14.417 Appnameremoved[28905:2938494] Downloading package.
> 2016-10-25 09:02:14.418 Appnameremoved[28905:2938494] [CodePush] Downloading update
> 2016-10-25 09:02:14.423 Appnameremoved[28905:2938494] -[CDVFileTransfer download:] [Line 422] File Transfer downloading file...
> 2016-10-25 09:02:17.775 Appnameremoved 28905:2938843] -[CDVFileTransferDelegate connection:didReceiveResponse:] [Line 760] Streaming to file /var/mobile/Containers/Data/Application/removed/Library/NoCloud/codepush/download/update.zip
> -[CDVFileTransfer download:] [Line 422] File Transfer downloading file...
> -[CDVFileTransferDelegate connection:didReceiveResponse:] [Line 760] Streaming to file /var/mobile/Containers/Data/Application/removed/Library/NoCloud/codepush/download/update.zip

In the output window of xcode, the downloading of the app starts (it’s downloading the complete app, 70MB, )

> 2016-10-25 09:02:19.610 [28905:2938494] Downloading 48715 of 73222318 bytes.

at 

> 2016-10-25 09:28:10.840 Appnameremoved[28905:2938494] Downloading 46039040 of 73222318 bytes.

the downloading stops and an error occurs:

> 2016-10-25 09:29:11.347 Appnameremoved[28905:2942338] FileTransferError {
>    body = "";
>    code = 3;
>    "http_status" = 200;
>    source = "https://codepush.blob.core.windows.net/storagev2/removed";
>    target = "file:///var/mobile/Containers/Data/Application/removed/Library/NoCloud/codepush/download/update.zip";
> }
> 2016-10-25 09:29:11.348 Appnameremoved[28905:2942338] File Transfer Error: The request timed out.
> 2016-10-25 09:29:11.901 Appnameremoved[28905:2938494] ERROR: [CodePush]  null
> 2016-10-25 09:29:11.901 Appnameremoved[28905:2938494] ERROR: [CodePush] An error occurred during sync.

After this, I tried to build the app on an iPad iOS9. No problems there. Significant difference was that the update downloaded a LOT faster. 
After that, I tried again to build on iPhone4s iOS8, but I made sure to keep the iPhone from going to sleep , by regularly scrolling a bit in the app. Now, the download succeeded (for the very first time!) 
Here is that output:


> 2016-10-25 10:51:36.791 appnameremoved[29123:2955200] [CodePush] Checking for update.
> 2016-10-25 10:51:37.970 appnameremoved[29123:2955200] [CodePush] An update is available. {"appVersion":"1.0.7","deploymentKey":"removed","description":"Test push naar 1.0.61","downloadUrl":"https://codepush.blob.core.windows.net/storagev2/removed","isMandatory":true,"label":"v4","packageHash”:"removed","packageSize":73222318,"failedInstall":false}
> 2016-10-25 10:51:37.972 appnameremoved[29123:2955200] [CodePush] Awaiting user action.
> 2016-10-25 10:51:37.973 appnameremoved[29123:2955200] Alerting user.
> 2016-10-25 10:52:15.264 appnameremoved[29123:2955200] Downloading package.
> 2016-10-25 10:52:15.265 appnameremoved[29123:2955200] [CodePush] Downloading update
> 2016-10-25 10:52:15.270 appnameremoved[29123:2955200] -[CDVFileTransfer download:] [Line 422] File Transfer downloading file...
> 2016-10-25 10:52:15.282 appnameremoved[29123:2955200] THREAD WARNING: ['FileTransfer'] took '12.507812' ms. Plugin should use a background thread.
> 2016-10-25 10:52:19.267 appnameremoved[29123:2955291] -[CDVFileTransferDelegate connection:didReceiveResponse:] [Line 760] Streaming to file /var/mobile/Containers/Data/Application/removed/Library/NoCloud/codepush/download/update.zip
> 2016-10-25 10:52:19.281 appnameremoved[29123:2955200] Downloading 15947 of 73222318 bytes.
> 

> 2016-10-25 11:26:44.299 appnameremoved[29123:2955200] Downloading 73203712 of 73222318 bytes.
> 2016-10-25 11:26:44.804 appnameremoved[29123:2958244] File Transfer Finished with response code 200
> 2016-10-25 11:26:44.809 appnameremoved[29123:2955200] Downloading 73222318 of 73222318 bytes.
> 2016-10-25 11:26:44.811 appnameremoved[29123:2958244] -[CDVFileTransferDelegate connectionDidFinishLoading:] [Line 626] File Transfer Download success
> 2016-10-25 11:26:44.936 appnameremoved[29123:2955200] [CodePush] Package download success: {"deploymentKey":"removed","description":"Test push naar 1.0.61","label":"v4","appVersion":"1.0.7","isMandatory":true,"packageHash":"removed","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/library-nosync/codepush/download/update.zip"}
> 2016-10-25 11:26:44.937 appnameremoved[29123:2955200] Installing update
> 2016-10-25 11:26:44.938 appnameremoved[29123:2955200] [CodePush] Installing update
> 2016-10-25 11:32:44.448 appnameremoved[29123:2955200] Received memory warning.
> 2016-10-25 11:32:44.452 appnameremoved[29123:2955293] void SendDelegateMessage(NSInvocation *): delegate (webView:decidePolicyForNavigationAction:request:frame:decisionListener:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode
> 2016-10-25 11:32:53.846 appnameremoved[29123:2955200] [CodePush] Install succeeded.

Could it be that the “sleep mode” is interfering with updating the code? 

Also, it looks like the update is downloading the complete app (70MB) (thus forcing it to take a very long time), instead of only the adjusted files (1 javascript and 1 textfile). Is this expected behavior (I hope not)? 
I think if we can bring the downloadtime down to the expected 200K, the suggested sleepmode-issue will be prevented all together.

Hope to hear from you

**Comment by max-mironov** [comment] 2017-02-28 11:52
Hello @MrWillow, @Gerarddus. My apologize for slow response, but is the issue still reproducing on your side? You said that you are on v1.8.2-beta and in [v.1.9.1-beta ](https://github.com/Microsoft/cordova-plugin-code-push/releases/tag/v1.9.1-beta) download speed was improved globally and updates are now distributed using a CDN, so this may help. 

Also regarding your second question about app download size - as it is stated [here ](https://github.com/Microsoft/cordova-plugin-code-push#releasing-updates): 

> The CodePush client supports differential updates, so even though you are releasing your app code on every update, your end users will only actually download the files they need. The service handles this automatically so that you can focus on creating awesome apps and we can worry about optimizing end user downloads.

So users will not dl the whole app updates each time but they have to dl it at least once so that the plugin will be able to determine which files are already existing.
Please let us know if it helps.

**Comment by max-mironov** [comment] 2017-03-07 07:09
@MrWillow, @Gerarddus - Guys, do you have a chance to look at this?

**Comment by Gerarddus** [comment] 2017-03-07 08:01
Hi @max-mironov ,
Thanks for your answer! For now we abandoned codepush in the project we were working on, we could not get it right..... I'll try to give codepush 1.9.1. update another go in a different project soon. It'll take some time, but I'll report here. Thanks!

**Comment by max-mironov** [comment] 2017-03-07 08:40
Thanks @Gerarddus for quick reply. I'll close the issue for now, feel free to reopen or create a new one if you see any. Thank you!

**Closed by max-mironov** 2017-03-07 08:40 UTC
Labels: investigating, waiting-for-clarification
