### ISSUE TITLE
Is there a way to get the reason for a rollback?

### ISSUE THREAD

**Issue by pke** [Microsoft/cordova-plugin-code-push#140] opened 2016-06-15 22:01 UTC
For some devices I see a rollback in the deployment history. Is there a way in the CLI to get details about why rollbacks were performed? I have no logging on those devices and cannot check them.

**Comment by lostintangent** [comment] 2016-06-15 22:31
@pke Not currently. A rollback happens when an update is installed and  `codePush.notifyApplication` (or `codePush.sync` which calls it internally) aren't called before the app is restarted again. In practice, this happens in two scenarios:

1. The app doesn't call the aforementioned methods on app start, and therefore, after the app is restarted in order to install an update, the app isn't successfully marked as successful. In most cases, app's that fall in this bucket are calling `sync` on resume, and therefore, a rollback could happen if the end user didn't resume the app at least once before the OS killed it. This is why our getting started recommends calling `sync` on start, and then optionally in other places. Can you verify that this isn't your problem?

2. The app crashed after trying to run the new update. In this case, we plan to eventually integrate more with crash reporting solutions, since we don't want to try to reinvent the wheel for a very well problem, as opposed to help shed light on the rollback and then connect the dots between that occurrence and the crash report that resulted in it. 

Are you using anything for crash reporting (e.g. Crashlytics, HockeyApp)? If so, have you seen any stacks show up?

**Comment by pke** [comment] 2016-06-16 00:51
We are not using any crash reporting atm.

I call the sync function in my react apps mount callback like this:

```
function startApp() {
  render(
    <Root/>,
    document.getElementById("app"),
    () => {
      if (navigator.splashscreen) {
        setTimeout(() => {
          navigator.splashscreen.hide()
        }, 10)
      }
      if (window.codePush) {
        const update = () => {
          window.codePush.sync(null, {
            deploymentKey: CONFIG.codepush,
          })
        }
        document.addEventListener("resume", update)
        update()
      }
    }
  )
}

if (window.cordova) {
  document.addEventListener("deviceready", startApp)
} else {
  startApp()
}
```

I had a problem before that was caused by loading the apps code using `<script src="bundle.js" async/>`. The async attribute caused all kind of weird effects (splashscreen not hiding) so maybe this was also the case for the rollback. I will try more with the updated app deploy, that does not use the `async` attribute on the script tag.

**Comment by lostintangent** [comment] 2016-06-16 01:06
Yeah in your case, you're calling sync on app start, so that's good. It's possible that the issue you had with the async script loading could have also caused some timing issue that led to a rollback. Let us know if you encounter any new issues now that you've fixed that problem.

**Closed** 2017-09-19 18:14 UTC
Labels: enhancement

**Comment by pke** [comment] 2017-09-19 18:22
Closing issues left and right, reminds me of the WinJS project. Care to explain why those issues are no longer relevant/worked on?

**Comment by pniko** [comment] 2017-09-19 19:11
Hi @pke, this issue is relevant and being worked on, but was being tracked in too many repos/places. This is a bigger ticket item for us which we will be announcing towards the end of the year. The way CodePush currently detects the need to rollback is too insufficient to provide you with any detailed information. In order to tackle this we are working to integrate a much more robust crash handler, new rollback process and better API/web access to log information. It's on our roadmap for this year.

**Comment by ryanvanderpol** [comment] 2017-10-25 18:41
@pniko You say this is being tracked "in too many places"; can you please link to where the "official" version of this is being tracked?  This is a pretty critical issue for us right now as roughly 15% of all our CodePush updates are being rolled back and we have absolutely zero visibility into what's going on.

**Comment by luckyycool** [comment] 2018-01-20 17:58
For me it is almost 70% rollbacks with no visibility what went wrong. Are we still waiting for the solution ??

**Comment by jpike88** [comment] 2018-02-09 05:17
At the very least, you guys can tell me which code push version the rollbacks are rolling back to. It blows my mind how this wasn't an ESSENTIAL addition to the product. It's basically saying 'something went wrong' with no clue as to why.

I put in the time and effort to invest in integrating this product into my application, and I feeling let down.

This, in addition to Appcenter's sluggish support for Cordova projects is why I'm starting to have second thoughts. Microsoft bought you guys, they should have the funding to give this entire product a kick up the butt. I (and I'm sure others) are willing to pay money for a stable, quality product, but so far I'm seeing out-of-the-garage open-source project progress and responsiveness. Incredibly disappointing.

**Comment by pke** [comment] 2018-02-09 09:34
I haven given up all hope for this plugin and codepush in general. I have removed it from all our apps. I suggest investing in PWA (Progressive Web Apps) which can be updated without the need of codepush.

**Comment by jpike88** [comment] 2018-02-09 09:45
Problem is that my app requires offline capability, and has some pretty deep cordova integration (qr code scanner etc)... if you have any ideas fire away.

**Comment by pke** [comment] 2018-02-09 10:33
Offline can be done using Service Workers in PWA. As for QR code scanner there is the WebRTC protocol which could also feed video data. The QR detection would then work in JS, which might be fast enough.
In any case you can code your app based on the devices capabilities. So we have code like this:
`export const canScan = () => window.cordova && window.cordova.plugins && !!window.cordova.plugins.barcodeScanner`

**Comment by afilp** [comment] 2018-02-23 09:08
@pniko Like @ryanvanderpol said "You say this is being tracked "in too many places"; can you please link to where the "official" version of this is being tracked?" 

Thanks!

**Comment by andreujuanc** [comment] 2018-06-27 14:45
I would love to get the rollback reason/cause and device info: Android version? Make/model? locale, etc.

**Comment by pke** [comment] 2018-06-27 21:36
I am afraid this will ever be implemented. I opened this issue 2 years ago.

**Comment by andreujuanc** [comment] 2018-06-27 22:05
I know , just wanted to leave my feedback x)

**Comment by pniko** [comment] 2018-06-28 00:19
Never say never. 😉

https://github.com/pniko/AppCenter-SDK-Android/tree/develop/sdk/appcenter-assets/src/main/java/com/microsoft/appcenter/assets

**Comment by andreujuanc** [comment] 2018-06-28 09:17
@pniko Ohhhh, nice!! Right now some of my users are experiencing a rollback. I know because of appcenter numbers, but I can't figure out why.

If this comes, ill be so, SO happy.

**Comment by pniko** [comment] 2018-06-28 14:45
It's coming. Redoing our crash pipeline right now so we can add in sourcemaps for Android while working on new App Center SDK's to replace the current CodePush ones with enhanced rollback support. There's an Apple SDK in flight as well so we can fully support brownfield apps in the future.

https://github.com/pniko/AppCenter-SDK-Apple/tree/develop/AppCenterAssets/AppCenterAssets

**Comment by afilp** [comment] 2019-04-17 12:43
@patniko Thanks, do we have it now supported in latest code-push release?

**Comment by anthonyhumphreys** [comment] 2019-05-31 10:14
Any updates on this?

**Comment by blueberry6401** [comment] 2019-12-24 07:11
I'm encountering rollback on  my own device without any crashing. Is there any way to know the cause, or  how to integrate any bug tracker to let them know what the bug is? I'm using bugsnag and don't receive any error report.
