### ISSUE TITLE
-[CodePush getStartPageURLForLocalPackage:]

### ISSUE THREAD

**Issue by interator** [Microsoft/cordova-plugin-code-push#414] opened 2018-05-23 16:08 UTC
### Description
Added the plugin, works fine with android but crashed on iOS device (ver10.3.3) and on simulator (ver11.3).
I'm getting this exception:
2018-05-23 18:52:58.415056+0300 JWed Match[1279:942251] [CodePush] Installing update
2018-05-23 18:53:00.485798+0300 JWed Match[1279:942251] [CodePush] Applying full update
2018-05-23 18:53:28.720620+0300 JWed Match[1279:942313] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[4]'
*** First throw call stack:
(0x1843d2fe0 0x182e34538 0x1842b42d8 0x1842c0030 0x1000974a4 0x10009589c 0x100721a50 0x100721a10 0x10072f990 0x100731630 0x10073139c 0x183493100 0x183492cac)
libc++abi.dylib: terminating with uncaught exception of type NSException

the exception occurs on this function:
- (NSURL *)getStartPageURLForLocalPackage:(NSString*)packageLocation {
    if (packageLocation) {
        NSString* startPage = [self getConfigLaunchUrl];
        NSString* libraryLocation = [NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES) objectAtIndex:0];
        NSArray* realLocationArray = @[libraryLocation, @"NoCloud", packageLocation, @"www", startPage];
        NSString* realStartPageLocation = [NSString pathWithComponents:realLocationArray];
        if ([[NSFileManager defaultManager] fileExistsAtPath:realStartPageLocation]) {
            return [NSURL fileURLWithPath:realStartPageLocation];
        }
    }

    return nil;
}

because startPage=nil and it crash on this row:
NSArray* realLocationArray = @[libraryLocation, @"NoCloud", packageLocation, @"www", startPage];

### Additional Information
* cordova-plugin-code-push version:  1.11.10 
* List of installed plugins:
cc.fovea.cordova.purchase 7.1.3 "Purchase"
code-push 2.0.4 "CodePushAcquisition"
cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-appcenter-analytics 0.1.4 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.1.4 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.1.3 "App Center shared code for Cordova"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-code-push 1.11.10 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-intercom 5.1.1 "Intercom"
cordova-plugin-listpicker 2.2.2 "ListPicker"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.4-dev "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova.plugins.diagnostic 4.0.5 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
pushwoosh-cordova-plugin 7.2.5 "Pushwoosh"
* Cordova version: 8.0.0
* iOS/Android/Windows version:
  android 7.1.0
  ios 4.5.4
* Does this reproduce on a debug build or release build? 
debug
* Does this reproduce on a simulator, or only on a physical device?
simulator and physical device

**Comment by alexandergoncharov** [comment] 2018-05-25 15:19
Hi @interator ,
Thanks for reporting!

Unfortunately I can't reproduce your issue. Could you please provide test project with reproducing issue and detailed repro-steps?
It would really help me to reproduce your issue and find the reason of issue.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment] 2018-05-28 06:07
Good news!

Thanks for keeping in touch. I'll close this issue for now as it was resolved but please feel free to reopen it if you will have any questions.

Thanks,
Alexander

**Closed by alexandergoncharov** 2018-05-28 06:07 UTC
Labels: bug, iOS, waiting-for-clarification
