### ISSUE TITLE
Most of the deployment are downloaded but not installed

### ISSUE THREAD

**Issue by talavidan4** [Microsoft/cordova-plugin-code-push#409] opened 2018-05-09 08:13 UTC
Hi everybody,

I work with code push more than a year, my last deployment was two month ago.
Today i pushed a deployment to appcenter, both - ios and android,
expecting  my app will updated like previous deployments.

The app get tested on 89 Android Devices of all kinds, and 13 ios devices as well.
This is the report of appcenter about active devices with the updated version:

**Android:**
![image](https://user-images.githubusercontent.com/6347078/39803001-4f83beb8-5378-11e8-994f-84ec2ce228a7.png)

**Ios:**
![image](https://user-images.githubusercontent.com/6347078/39803058-79f045ea-5378-11e8-9da3-68a4dac21242.png)

I never saw ratio like this in my deployments before, till i saw one active device in Android -
i thought that installation can't occur at all.

### Additional Information
The app build with phonegap:
![image](https://user-images.githubusercontent.com/6347078/39803297-4db52fbc-5379-11e8-8534-b04a5657c666.png)

Plugin List:
![image](https://user-images.githubusercontent.com/6347078/39803362-809d4888-5379-11e8-9309-80861be239f5.png)

**Comment by Zakeelm** [comment] 2018-05-09 22:30
Can you let me know when you're calling `sync()` and can you also tell me what your sync options are?

**Comment by talavidan4** [comment] 2018-05-10 06:19
Hi @Zakeelm,
I'm calling `sync()` on cordova `deviceready` event, the sync options is the default, i'm passing
only the syncCallback parameter - `codePush.sync(syncStatus);`

**Comment by hobzcalvin** [comment] 2018-05-10 20:49
This may be a duplicate of #374 which was fixed in v1.11.9; you have v1.11.3 which is long before that issue was fixed.

**Comment by talavidan4** [comment] 2018-05-13 04:31
Hi @hobzcalvin,
I've got no file name in assets folder which correspond to the pattern:
`!.svn:!.git:!.ds_store:!*.scc:.*:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~`
Anyway i'll update the plugin version and try it again, altough it used to work fine.

**Comment by alexandergoncharov** [comment] 2018-05-14 16:25
Hi @talavidan4 ,
Thanks for reporting.

Do you have any logs from issue installing?
And have you tried to get this update on your device just for testing?

Thanks,
Alexander

**Comment by talavidan4** [comment] 2018-05-15 10:25
Hi @alexandergoncharov ,
I tried to update the version (code-push 1.11.10) on my device as well, with no luck.
There are few users which thier devices get updated.
As i mentioned above - i'm using `sync` to handle all the process for me.
I followed the update on my device - and i can tell that Package get downloaded because i'm listen to 'syncCallback?' and checking the status:
 `case SyncStatus.INSTALLING_UPDATE` been hitted.

From codePush docs:
> INSTALLING_UPDATE: An available update was downloaded and is about to be installed

Meanning  - still not installed.

In the same switch case i checked for `codePush.getCurrentPackage` and it holds null.
Is there a way to catch install erros in the same process describe here? 

Thanks a lot

**Comment by alexandergoncharov** [comment] 2018-05-15 16:03
@talavidan4 , Is it possible to provide test project with reproducing issue? It would be helpful for me for investigating it.

About checking install error: It should be in logs if you run app on AndroidStudio/Xcode/Vs Code debugger in debug mode.

Thanks,
Alexander

**Comment by talavidan4** [comment] 2018-05-21 09:47
Hi @alexandergoncharov ,
Sorry for the delay - i'm sitting for days, trying to figger out what went wrong...
At some point i decided to built a new project and i added all the plugins and platforns from scratch.
I noticed a new plugin that was missing in my master porject - `cordova-plugin-zip`.
Strange that in the past everything worked as expected without this plugin, but this was the missing peace - i just added this one to my master and 12 days without sleeping are comes to an end :)

**Comment by alexandergoncharov** [comment] 2018-05-21 13:51
@talavidan4, Good news =)
Thanks for keeping us up to date!

As issue is resolved I'll close this issue. But feel free to reopen it if you will have any questions.

Thanks,
Alexander

**Closed by alexandergoncharov** 2018-05-21 13:51 UTC
Labels: waiting-for-clarification
