### ISSUE TITLE
window.codePush freezes the app and the browser

### ISSUE THREAD

**Issue by kosalanuwan** [Microsoft/cordova-plugin-code-push#193] opened 2016-11-28 18:37 UTC
When I try to access the `window.codePush` object in my app it just freezes. Does nothing.
``` js
  $scope.update = function() {
    try {
      if (window.codePush) {
        alert('codepush found');
      } else {
        alert('codepush not found');
      }
    } catch (error) {
      alert('codepush crashed');
    }
  }
```
This doesn't return any alert when I run `ionic serve` or `ionic run android` My configurations;
Ionic CLI - 2.1.13
Cordova - 6.4.0
Cordova Android - 6.1.0

List of plugins added;
code-push 1.9.0-beta "CodePushAcquisition"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-code-push 1.9.2-beta "CodePush"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-dialogs 1.3.0 "Notification"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by max-mironov** [comment] 2016-12-20 07:09
Hi,
I've tried to reproduce the issue with Ionic App for cordova-plugin-code-push 1.9.2-beta with the code chunk you provided above but with no success. 
Can you please try to reproduce it again and if the issue is still there would it be possible to provide more details (e.g. emulator/device you are running) or share the small test project where the issue can be reproduced?

**Comment by max-mironov** [comment] 2017-02-07 11:17
@kosalanuwan - do you still face this issue? Please let us know if the issue still exists for you or we can close this for now?

**Comment by max-mironov** [comment] 2017-02-14 15:25
Closing the issue for now, feel free to reopen or create a new one if you still face that problem.

**Closed by max-mironov** 2017-02-14 15:25 UTC
